DROP TABLE IF EXISTS products;

DROP TABLE IF EXISTS kinds;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS subcategories;
DROP TABLE IF EXISTS units;
DROP TABLE IF EXISTS types;
DROP TABLE IF EXISTS seasons;
DROP TABLE IF EXISTS brands;
DROP TABLE IF EXISTS origins;
