// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attributes.sql

package db

import (
	"context"
)

const createAttributeValue = `-- name: CreateAttributeValue :one
INSERT INTO attributes_values (
  attribute,
  value
) VALUES (
    $1, $2
) RETURNING id, attribute, value
`

type CreateAttributeValueParams struct {
	Attribute string `json:"attribute"`
	Value     string `json:"value"`
}

func (q *Queries) CreateAttributeValue(ctx context.Context, arg CreateAttributeValueParams) (AttributesValue, error) {
	row := q.db.QueryRowContext(ctx, createAttributeValue, arg.Attribute, arg.Value)
	var i AttributesValue
	err := row.Scan(&i.ID, &i.Attribute, &i.Value)
	return i, err
}

const getAttributeValue = `-- name: GetAttributeValue :one
SELECT id, attribute, value FROM attributes_values
WHERE id = $1
`

func (q *Queries) GetAttributeValue(ctx context.Context, id int64) (AttributesValue, error) {
	row := q.db.QueryRowContext(ctx, getAttributeValue, id)
	var i AttributesValue
	err := row.Scan(&i.ID, &i.Attribute, &i.Value)
	return i, err
}

const listAttributeValues = `-- name: ListAttributeValues :many
SELECT a.name, av.id, av.attribute, av.value
FROM attributes a
INNER JOIN attributes_values av
ON a.name = av.attribute
ORDER BY value
LIMIT $1
OFFSET $2
`

type ListAttributeValuesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListAttributeValuesRow struct {
	Name      string `json:"name"`
	ID        int64  `json:"id"`
	Attribute string `json:"attribute"`
	Value     string `json:"value"`
}

func (q *Queries) ListAttributeValues(ctx context.Context, arg ListAttributeValuesParams) ([]ListAttributeValuesRow, error) {
	rows, err := q.db.QueryContext(ctx, listAttributeValues, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAttributeValuesRow{}
	for rows.Next() {
		var i ListAttributeValuesRow
		if err := rows.Scan(
			&i.Name,
			&i.ID,
			&i.Attribute,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttributeValue = `-- name: UpdateAttributeValue :exec
UPDATE attributes_values 
SET value = $2
WHERE id = $1
`

type UpdateAttributeValueParams struct {
	ID    int64  `json:"id"`
	Value string `json:"value"`
}

func (q *Queries) UpdateAttributeValue(ctx context.Context, arg UpdateAttributeValueParams) error {
	_, err := q.db.ExecContext(ctx, updateAttributeValue, arg.ID, arg.Value)
	return err
}
