// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cashbox.sql

package db

import (
	"context"
)

const createCashbox = `-- name: CreateCashbox :one
INSERT INTO cashboxes (
  code,
  is_active
) 
VALUES ( $1, $2 )
RETURNING id, code, is_active, created_at
`

type CreateCashboxParams struct {
	Code     string `json:"code"`
	IsActive bool   `json:"isActive"`
}

func (q *Queries) CreateCashbox(ctx context.Context, arg CreateCashboxParams) (Cashbox, error) {
	row := q.db.QueryRowContext(ctx, createCashbox, arg.Code, arg.IsActive)
	var i Cashbox
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getCashbox = `-- name: GetCashbox :one
SELECT id, code, is_active, created_at FROM cashboxes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCashbox(ctx context.Context, id int64) (Cashbox, error) {
	row := q.db.QueryRowContext(ctx, getCashbox, id)
	var i Cashbox
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listCashboxes = `-- name: ListCashboxes :many
SELECT id, code, is_active, created_at FROM cashboxes
WHERE id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListCashboxesParams struct {
	ID     int64 `json:"id"`
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCashboxes(ctx context.Context, arg ListCashboxesParams) ([]Cashbox, error) {
	rows, err := q.db.QueryContext(ctx, listCashboxes, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cashbox{}
	for rows.Next() {
		var i Cashbox
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
