// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cashbox.sql

package db

import (
	"context"
)

const addAccountBalance = `-- name: AddAccountBalance :one
UPDATE shifts_accounts_balances
SET balance = balance + $1
WHERE account_id = $2
AND shift_id = $3
RETURNING account_id, shift_id, balance
`

type AddAccountBalanceParams struct {
	Amount    int64 `json:"amount"`
	AccountID int64 `json:"accountId"`
	ShiftID   int64 `json:"shiftId"`
}

func (q *Queries) AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (ShiftsAccountsBalance, error) {
	row := q.db.QueryRowContext(ctx, addAccountBalance, arg.Amount, arg.AccountID, arg.ShiftID)
	var i ShiftsAccountsBalance
	err := row.Scan(&i.AccountID, &i.ShiftID, &i.Balance)
	return i, err
}

const createCashbox = `-- name: CreateCashbox :one
INSERT INTO cashboxes (
  code,
  name,
  is_active
) 
VALUES ( $1, $2, $3 )
RETURNING id, name, code, is_active, created_at
`

type CreateCashboxParams struct {
	Code     string `json:"code"`
	Name     string `json:"name"`
	IsActive bool   `json:"isActive"`
}

func (q *Queries) CreateCashbox(ctx context.Context, arg CreateCashboxParams) (Cashbox, error) {
	row := q.db.QueryRowContext(ctx, createCashbox, arg.Code, arg.Name, arg.IsActive)
	var i Cashbox
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createCashboxAccount = `-- name: CreateCashboxAccount :one
INSERT INTO cashbox_accounts (
  name
) 
VALUES ($1 )
RETURNING id, name
`

func (q *Queries) CreateCashboxAccount(ctx context.Context, name string) (CashboxAccount, error) {
	row := q.db.QueryRowContext(ctx, createCashboxAccount, name)
	var i CashboxAccount
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getCashbox = `-- name: GetCashbox :one
SELECT id, name, code, is_active, created_at FROM cashboxes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCashbox(ctx context.Context, id int64) (Cashbox, error) {
	row := q.db.QueryRowContext(ctx, getCashbox, id)
	var i Cashbox
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getCashboxAccount = `-- name: GetCashboxAccount :one
SELECT id, name FROM cashbox_accounts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCashboxAccount(ctx context.Context, id int64) (CashboxAccount, error) {
	row := q.db.QueryRowContext(ctx, getCashboxAccount, id)
	var i CashboxAccount
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, name FROM cashbox_accounts
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListAccountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]CashboxAccount, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CashboxAccount{}
	for rows.Next() {
		var i CashboxAccount
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCashboxes = `-- name: ListCashboxes :many
SELECT id, name, code, is_active, created_at FROM cashboxes
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListCashboxesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCashboxes(ctx context.Context, arg ListCashboxesParams) ([]Cashbox, error) {
	rows, err := q.db.QueryContext(ctx, listCashboxes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cashbox{}
	for rows.Next() {
		var i Cashbox
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCashbox = `-- name: UpdateCashbox :one
UPDATE cashboxes
SET code = $2,
name = $3,
is_active = $4
WHERE id = $1
RETURNING id, name, code, is_active, created_at
`

type UpdateCashboxParams struct {
	ID       int64  `json:"id"`
	Code     string `json:"code"`
	Name     string `json:"name"`
	IsActive bool   `json:"isActive"`
}

func (q *Queries) UpdateCashbox(ctx context.Context, arg UpdateCashboxParams) (Cashbox, error) {
	row := q.db.QueryRowContext(ctx, updateCashbox,
		arg.ID,
		arg.Code,
		arg.Name,
		arg.IsActive,
	)
	var i Cashbox
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const updateCashboxAccount = `-- name: UpdateCashboxAccount :one
UPDATE cashbox_accounts
SET name = $2
WHERE id = $1
RETURNING id, name
`

type UpdateCashboxAccountParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateCashboxAccount(ctx context.Context, arg UpdateCashboxAccountParams) (CashboxAccount, error) {
	row := q.db.QueryRowContext(ctx, updateCashboxAccount, arg.ID, arg.Name)
	var i CashboxAccount
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
