// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cashbox.sql

package db

import (
	"context"
)

const addAccountBalance = `-- name: AddAccountBalance :one
UPDATE cashbox_accounts
SET balance = balance + $1
WHERE id = $2
RETURNING id, type, shift_id, currency_code, opening_balance, balance
`

type AddAccountBalanceParams struct {
	Amount int64 `json:"amount"`
	ID     int64 `json:"id"`
}

func (q *Queries) AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (CashboxAccount, error) {
	row := q.db.QueryRowContext(ctx, addAccountBalance, arg.Amount, arg.ID)
	var i CashboxAccount
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ShiftID,
		&i.CurrencyCode,
		&i.OpeningBalance,
		&i.Balance,
	)
	return i, err
}

const createCashbox = `-- name: CreateCashbox :one
INSERT INTO cashboxes (
  code,
  name,
  is_active
) 
VALUES ( $1, $2, $3 )
RETURNING id, name, code, is_active, created_at
`

type CreateCashboxParams struct {
	Code     string `json:"code"`
	Name     string `json:"name"`
	IsActive bool   `json:"isActive"`
}

func (q *Queries) CreateCashbox(ctx context.Context, arg CreateCashboxParams) (Cashbox, error) {
	row := q.db.QueryRowContext(ctx, createCashbox, arg.Code, arg.Name, arg.IsActive)
	var i Cashbox
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const createCashboxAccount = `-- name: CreateCashboxAccount :one
INSERT INTO cashbox_accounts (
  type,
  shift_id,
  currency_code,
  opening_balance,
  balance
) 
VALUES ($1, $2, $3, $4, $5)
RETURNING id, type, shift_id, currency_code, opening_balance, balance
`

type CreateCashboxAccountParams struct {
	Type           string `json:"type"`
	ShiftID        int64  `json:"shiftId"`
	CurrencyCode   string `json:"currencyCode"`
	OpeningBalance int64  `json:"openingBalance"`
	Balance        int64  `json:"balance"`
}

func (q *Queries) CreateCashboxAccount(ctx context.Context, arg CreateCashboxAccountParams) (CashboxAccount, error) {
	row := q.db.QueryRowContext(ctx, createCashboxAccount,
		arg.Type,
		arg.ShiftID,
		arg.CurrencyCode,
		arg.OpeningBalance,
		arg.Balance,
	)
	var i CashboxAccount
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ShiftID,
		&i.CurrencyCode,
		&i.OpeningBalance,
		&i.Balance,
	)
	return i, err
}

const getCashbox = `-- name: GetCashbox :one
SELECT id, name, code, is_active, created_at FROM cashboxes
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCashbox(ctx context.Context, id int64) (Cashbox, error) {
	row := q.db.QueryRowContext(ctx, getCashbox, id)
	var i Cashbox
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getCashboxAccount = `-- name: GetCashboxAccount :one
SELECT id, type, shift_id, currency_code, opening_balance, balance FROM cashbox_accounts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCashboxAccount(ctx context.Context, id int64) (CashboxAccount, error) {
	row := q.db.QueryRowContext(ctx, getCashboxAccount, id)
	var i CashboxAccount
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ShiftID,
		&i.CurrencyCode,
		&i.OpeningBalance,
		&i.Balance,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, type, shift_id, currency_code, opening_balance, balance FROM cashbox_accounts
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListAccountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]CashboxAccount, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CashboxAccount{}
	for rows.Next() {
		var i CashboxAccount
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ShiftID,
			&i.CurrencyCode,
			&i.OpeningBalance,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCashboxes = `-- name: ListCashboxes :many
SELECT id, name, code, is_active, created_at FROM cashboxes
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListCashboxesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCashboxes(ctx context.Context, arg ListCashboxesParams) ([]Cashbox, error) {
	rows, err := q.db.QueryContext(ctx, listCashboxes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cashbox{}
	for rows.Next() {
		var i Cashbox
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
