// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: coupon.sql

package db

import (
	"context"
	"time"
)

const createCoupon = `-- name: CreateCoupon :one
INSERT INTO coupons (
  code,
  status,
  discount_type,
  reason,
  client_id,
  valid_until
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING code, status, discount_type, reason, client_id, valid_until, created_at
`

type CreateCouponParams struct {
	Code         string       `json:"code"`
	Status       CouponStatus `json:"status"`
	DiscountType DiscountType `json:"discountType"`
	Reason       string       `json:"reason"`
	ClientID     int64        `json:"clientId"`
	ValidUntil   time.Time    `json:"validUntil"`
}

func (q *Queries) CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error) {
	row := q.db.QueryRowContext(ctx, createCoupon,
		arg.Code,
		arg.Status,
		arg.DiscountType,
		arg.Reason,
		arg.ClientID,
		arg.ValidUntil,
	)
	var i Coupon
	err := row.Scan(
		&i.Code,
		&i.Status,
		&i.DiscountType,
		&i.Reason,
		&i.ClientID,
		&i.ValidUntil,
		&i.CreatedAt,
	)
	return i, err
}

const getCoupon = `-- name: GetCoupon :one
SELECT code, status, discount_type, reason, client_id, valid_until, created_at FROM coupons
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetCoupon(ctx context.Context, code string) (Coupon, error) {
	row := q.db.QueryRowContext(ctx, getCoupon, code)
	var i Coupon
	err := row.Scan(
		&i.Code,
		&i.Status,
		&i.DiscountType,
		&i.Reason,
		&i.ClientID,
		&i.ValidUntil,
		&i.CreatedAt,
	)
	return i, err
}

const listCoupons = `-- name: ListCoupons :many
SELECT code, status, discount_type, reason, client_id, valid_until, created_at FROM coupons
ORDER BY code
LIMIT $1
OFFSET $2
`

type ListCouponsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCoupons(ctx context.Context, arg ListCouponsParams) ([]Coupon, error) {
	rows, err := q.db.QueryContext(ctx, listCoupons, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Coupon{}
	for rows.Next() {
		var i Coupon
		if err := rows.Scan(
			&i.Code,
			&i.Status,
			&i.DiscountType,
			&i.Reason,
			&i.ClientID,
			&i.ValidUntil,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCouponStatus = `-- name: UpdateCouponStatus :exec
UPDATE coupons 
  SET status = $2
WHERE code = $1
`

type UpdateCouponStatusParams struct {
	Code   string       `json:"code"`
	Status CouponStatus `json:"status"`
}

func (q *Queries) UpdateCouponStatus(ctx context.Context, arg UpdateCouponStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateCouponStatus, arg.Code, arg.Status)
	return err
}
