// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: currency.sql

package db

import (
	"context"
)

const createCurrency = `-- name: CreateCurrency :one
INSERT INTO currencies (
  name,
  code,
  symbol,
  value_in_default_currency 
) 
VALUES ( $1, $2, $3, $4 )
RETURNING code, name, symbol, is_default, value_in_default_currency
`

type CreateCurrencyParams struct {
	Name                   string `json:"name"`
	Code                   string `json:"code"`
	Symbol                 string `json:"symbol"`
	ValueInDefaultCurrency int64  `json:"valueInDefaultCurrency"`
}

func (q *Queries) CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error) {
	row := q.db.QueryRowContext(ctx, createCurrency,
		arg.Name,
		arg.Code,
		arg.Symbol,
		arg.ValueInDefaultCurrency,
	)
	var i Currency
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.IsDefault,
		&i.ValueInDefaultCurrency,
	)
	return i, err
}

const deleteCurrency = `-- name: DeleteCurrency :exec
delete from currencies
where code = $1
`

func (q *Queries) DeleteCurrency(ctx context.Context, code string) error {
	_, err := q.db.ExecContext(ctx, deleteCurrency, code)
	return err
}

const getCurrency = `-- name: GetCurrency :one
SELECT code, name, symbol, is_default, value_in_default_currency FROM currencies
WHERE code = $1 LIMIT 1
`

func (q *Queries) GetCurrency(ctx context.Context, code string) (Currency, error) {
	row := q.db.QueryRowContext(ctx, getCurrency, code)
	var i Currency
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.IsDefault,
		&i.ValueInDefaultCurrency,
	)
	return i, err
}

const getDefaultCurrency = `-- name: GetDefaultCurrency :one
SELECT code, name, symbol, is_default, value_in_default_currency FROM currencies
WHERE is_default = true
`

func (q *Queries) GetDefaultCurrency(ctx context.Context) (Currency, error) {
	row := q.db.QueryRowContext(ctx, getDefaultCurrency)
	var i Currency
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.IsDefault,
		&i.ValueInDefaultCurrency,
	)
	return i, err
}

const listCurrencies = `-- name: ListCurrencies :many
SELECT code, name, symbol, is_default, value_in_default_currency FROM currencies
ORDER BY code
LIMIT $1
OFFSET $2
`

type ListCurrenciesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCurrencies(ctx context.Context, arg ListCurrenciesParams) ([]Currency, error) {
	rows, err := q.db.QueryContext(ctx, listCurrencies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Currency{}
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.IsDefault,
			&i.ValueInDefaultCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
