// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: currency.sql

package db

import (
	"context"
)

const createCurrency = `-- name: CreateCurrency :one
INSERT INTO currencies (
  name,
  value_in_usd
) 
VALUES ( $1, $2 )
RETURNING id, name, value_in_usd
`

type CreateCurrencyParams struct {
	Name       string `json:"name"`
	ValueInUsd string `json:"valueInUsd"`
}

func (q *Queries) CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error) {
	row := q.db.QueryRowContext(ctx, createCurrency, arg.Name, arg.ValueInUsd)
	var i Currency
	err := row.Scan(&i.ID, &i.Name, &i.ValueInUsd)
	return i, err
}

const deleteCurrency = `-- name: DeleteCurrency :exec
delete from currencies
where id = $1
`

func (q *Queries) DeleteCurrency(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteCurrency, id)
	return err
}

const getCurrency = `-- name: GetCurrency :one
SELECT id, name, value_in_usd FROM currencies
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCurrency(ctx context.Context, id int64) (Currency, error) {
	row := q.db.QueryRowContext(ctx, getCurrency, id)
	var i Currency
	err := row.Scan(&i.ID, &i.Name, &i.ValueInUsd)
	return i, err
}

const listCurrencies = `-- name: ListCurrencies :many
SELECT id, name, value_in_usd FROM currencies
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListCurrenciesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListCurrencies(ctx context.Context, arg ListCurrenciesParams) ([]Currency, error) {
	rows, err := q.db.QueryContext(ctx, listCurrencies, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Currency{}
	for rows.Next() {
		var i Currency
		if err := rows.Scan(&i.ID, &i.Name, &i.ValueInUsd); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
