// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entry.sql

package db

import (
	"context"
)

const createEntryItem = `-- name: CreateEntryItem :one
INSERT INTO entries (
  cashbox_id,
  inventory_id,
  reference_type,
  reference_id,
  net_amount_in_default_currency
) 
VALUES ( $1, $2, $3, $4, $5)
RETURNING id, cashbox_id, inventory_id, reference_type, reference_id, net_amount_in_default_currency, created_at
`

type CreateEntryItemParams struct {
	CashboxID                  int64              `json:"cashboxId"`
	InventoryID                int64              `json:"inventoryId"`
	ReferenceType              EntryReferenceType `json:"referenceType"`
	ReferenceID                int64              `json:"referenceId"`
	NetAmountInDefaultCurrency int64              `json:"netAmountInDefaultCurrency"`
}

func (q *Queries) CreateEntryItem(ctx context.Context, arg CreateEntryItemParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntryItem,
		arg.CashboxID,
		arg.InventoryID,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.NetAmountInDefaultCurrency,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.CashboxID,
		&i.InventoryID,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.NetAmountInDefaultCurrency,
		&i.CreatedAt,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, cashbox_id, inventory_id, reference_type, reference_id, net_amount_in_default_currency, created_at FROM entries
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEntry(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.CashboxID,
		&i.InventoryID,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.NetAmountInDefaultCurrency,
		&i.CreatedAt,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT id, cashbox_id, inventory_id, reference_type, reference_id, net_amount_in_default_currency, created_at FROM entries
WHERE inventory_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListEntriesParams struct {
	InventoryID int64 `json:"inventoryId"`
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
}

func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntries, arg.InventoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.CashboxID,
			&i.InventoryID,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.NetAmountInDefaultCurrency,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
