// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: entry.sql

package db

import (
	"context"
	"database/sql"
)

const createEntryItem = `-- name: CreateEntryItem :one
INSERT INTO entries (
  inventory_id,
  reference_type,
  reference_id,
  -- either product id or asset id (one must be NULL)
  asset_id,
  product_id,
  quantity
) 
VALUES ( $1, $2, $3, $4, $5, $6)
RETURNING id, inventory_id, reference_type, reference_id, product_id, asset_id, quantity, created_at
`

type CreateEntryItemParams struct {
	InventoryID   int64              `json:"inventoryId"`
	ReferenceType EntryReferenceType `json:"referenceType"`
	ReferenceID   int64              `json:"referenceId"`
	AssetID       sql.NullInt64      `json:"assetId"`
	ProductID     sql.NullInt64      `json:"productId"`
	Quantity      int64              `json:"quantity"`
}

func (q *Queries) CreateEntryItem(ctx context.Context, arg CreateEntryItemParams) (Entry, error) {
	row := q.db.QueryRowContext(ctx, createEntryItem,
		arg.InventoryID,
		arg.ReferenceType,
		arg.ReferenceID,
		arg.AssetID,
		arg.ProductID,
		arg.Quantity,
	)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.InventoryID,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.ProductID,
		&i.AssetID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const getEntry = `-- name: GetEntry :one
SELECT id, inventory_id, reference_type, reference_id, product_id, asset_id, quantity, created_at FROM entries
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEntry(ctx context.Context, id int64) (Entry, error) {
	row := q.db.QueryRowContext(ctx, getEntry, id)
	var i Entry
	err := row.Scan(
		&i.ID,
		&i.InventoryID,
		&i.ReferenceType,
		&i.ReferenceID,
		&i.ProductID,
		&i.AssetID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const listEntries = `-- name: ListEntries :many
SELECT id, inventory_id, reference_type, reference_id, product_id, asset_id, quantity, created_at FROM entries
WHERE inventory_id = $1
ORDER BY id
LIMIT $2
OFFSET $3
`

type ListEntriesParams struct {
	InventoryID int64 `json:"inventoryId"`
	Limit       int32 `json:"limit"`
	Offset      int32 `json:"offset"`
}

func (q *Queries) ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error) {
	rows, err := q.db.QueryContext(ctx, listEntries, arg.InventoryID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Entry{}
	for rows.Next() {
		var i Entry
		if err := rows.Scan(
			&i.ID,
			&i.InventoryID,
			&i.ReferenceType,
			&i.ReferenceID,
			&i.ProductID,
			&i.AssetID,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
