// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: inventory.sql

package db

import (
	"context"
	"database/sql"
)

const addInventoryProduct = `-- name: AddInventoryProduct :one
INSERT INTO inventories_products (
  inventory_id,
  product_id,
  quantity
)
VALUES ( $1, $2, $3)
RETURNING product_id, inventory_id, quantity
`

type AddInventoryProductParams struct {
	InventoryID int64 `json:"inventoryId"`
	ProductID   int64 `json:"productId"`
	Quantity    int64 `json:"quantity"`
}

func (q *Queries) AddInventoryProduct(ctx context.Context, arg AddInventoryProductParams) (InventoriesProduct, error) {
	row := q.db.QueryRowContext(ctx, addInventoryProduct, arg.InventoryID, arg.ProductID, arg.Quantity)
	var i InventoriesProduct
	err := row.Scan(&i.ProductID, &i.InventoryID, &i.Quantity)
	return i, err
}

const createInventory = `-- name: CreateInventory :one
INSERT INTO inventories (
  name,
  code,
  longitude,
  latitude
) VALUES ( $1, $2, $3, $4)
RETURNING id, name, code, longitude, latitude, created_at
`

type CreateInventoryParams struct {
	Name      string          `json:"name"`
	Code      string          `json:"code"`
	Longitude sql.NullFloat64 `json:"longitude"`
	Latitude  sql.NullFloat64 `json:"latitude"`
}

func (q *Queries) CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, createInventory,
		arg.Name,
		arg.Code,
		arg.Longitude,
		arg.Latitude,
	)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Longitude,
		&i.Latitude,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInventory = `-- name: DeleteInventory :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteInventory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteInventory, id)
	return err
}

const deleteInventoryProduct = `-- name: DeleteInventoryProduct :exec
DELETE FROM inventories_products
WHERE inventory_id = $1
AND product_id = $2
`

type DeleteInventoryProductParams struct {
	InventoryID int64 `json:"inventoryId"`
	ProductID   int64 `json:"productId"`
}

func (q *Queries) DeleteInventoryProduct(ctx context.Context, arg DeleteInventoryProductParams) error {
	_, err := q.db.ExecContext(ctx, deleteInventoryProduct, arg.InventoryID, arg.ProductID)
	return err
}

const getInventory = `-- name: GetInventory :one
SELECT id, name, code, longitude, latitude, created_at FROM inventories
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetInventory(ctx context.Context, id int64) (Inventory, error) {
	row := q.db.QueryRowContext(ctx, getInventory, id)
	var i Inventory
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Longitude,
		&i.Latitude,
		&i.CreatedAt,
	)
	return i, err
}

const listInventories = `-- name: ListInventories :many
SELECT id, name, code, longitude, latitude, created_at FROM inventories
ORDER BY name
LIMIT $1
OFFSET $2
`

type ListInventoriesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListInventories(ctx context.Context, arg ListInventoriesParams) ([]Inventory, error) {
	rows, err := q.db.QueryContext(ctx, listInventories, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Inventory
	for rows.Next() {
		var i Inventory
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Longitude,
			&i.Latitude,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listInventoryProducts = `-- name: ListInventoryProducts :many
SELECT
  ip.inventory_id,
  ip.product_id,
  ip.quantity,
  p.name, 
  p.code
FROM inventories_products ip
JOIN products p ON p.id = ip.product_id
WHERE ip.inventory_id = $1
ORDER BY p.name
`

type ListInventoryProductsRow struct {
	InventoryID int64  `json:"inventoryId"`
	ProductID   int64  `json:"productId"`
	Quantity    int64  `json:"quantity"`
	Name        string `json:"name"`
	Code        string `json:"code"`
}

func (q *Queries) ListInventoryProducts(ctx context.Context, inventoryID int64) ([]ListInventoryProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listInventoryProducts, inventoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListInventoryProductsRow
	for rows.Next() {
		var i ListInventoryProductsRow
		if err := rows.Scan(
			&i.InventoryID,
			&i.ProductID,
			&i.Quantity,
			&i.Name,
			&i.Code,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInventory = `-- name: UpdateInventory :exec
UPDATE inventories 
SET name = $2
WHERE id = $1
`

type UpdateInventoryParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateInventory(ctx context.Context, arg UpdateInventoryParams) error {
	_, err := q.db.ExecContext(ctx, updateInventory, arg.ID, arg.Name)
	return err
}

const updateInventoryProduct = `-- name: UpdateInventoryProduct :exec
UPDATE inventories_products
SET quantity = $3
WHERE inventory_id = $1
AND product_id = $2
`

type UpdateInventoryProductParams struct {
	InventoryID int64 `json:"inventoryId"`
	ProductID   int64 `json:"productId"`
	Quantity    int64 `json:"quantity"`
}

func (q *Queries) UpdateInventoryProduct(ctx context.Context, arg UpdateInventoryProductParams) error {
	_, err := q.db.ExecContext(ctx, updateInventoryProduct, arg.InventoryID, arg.ProductID, arg.Quantity)
	return err
}
