// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoice.sql

package db

import (
	"context"
)

const addSalesInvoiceProduct = `-- name: AddSalesInvoiceProduct :one
INSERT INTO sales_invoice_products (
  invoice_id,
  product_id,
  quantity
) 
VALUES ( $1, $2, $3 )
RETURNING invoice_id, product_id, quantity, created_at
`

type AddSalesInvoiceProductParams struct {
	InvoiceID int64 `json:"invoiceId"`
	ProductID int64 `json:"productId"`
	Quantity  int64 `json:"quantity"`
}

func (q *Queries) AddSalesInvoiceProduct(ctx context.Context, arg AddSalesInvoiceProductParams) (SalesInvoiceProduct, error) {
	row := q.db.QueryRowContext(ctx, addSalesInvoiceProduct, arg.InvoiceID, arg.ProductID, arg.Quantity)
	var i SalesInvoiceProduct
	err := row.Scan(
		&i.InvoiceID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const countReturnInvoicesThisYear = `-- name: CountReturnInvoicesThisYear :one
SELECT count(*) FROM return_invoices
WHERE created_at >= date_trunc('year', now() AT TIME ZONE 'UTC')
`

func (q *Queries) CountReturnInvoicesThisYear(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countReturnInvoicesThisYear)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSalesInvoicesThisYear = `-- name: CountSalesInvoicesThisYear :one
SELECT count(*) FROM sales_invoices
WHERE created_at >= date_trunc('year', now() AT TIME ZONE 'UTC')
`

func (q *Queries) CountSalesInvoicesThisYear(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSalesInvoicesThisYear)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReturnInvoice = `-- name: CreateReturnInvoice :one
INSERT INTO return_invoices (
  invoice_number,
  sales_invoice_id
) 
VALUES ( $1, $2 )
RETURNING id, invoice_number, sales_invoice_id, created_at
`

type CreateReturnInvoiceParams struct {
	InvoiceNumber  string `json:"invoiceNumber"`
	SalesInvoiceID int64  `json:"salesInvoiceId"`
}

func (q *Queries) CreateReturnInvoice(ctx context.Context, arg CreateReturnInvoiceParams) (ReturnInvoice, error) {
	row := q.db.QueryRowContext(ctx, createReturnInvoice, arg.InvoiceNumber, arg.SalesInvoiceID)
	var i ReturnInvoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.SalesInvoiceID,
		&i.CreatedAt,
	)
	return i, err
}

const createSalesInvoice = `-- name: CreateSalesInvoice :one
INSERT INTO sales_invoices (
  cashbox_id,
  invoice_number,
  inventory_id,
  client_id,
  amount,
  net_amount,
  discount,
  currency_id
) 
VALUES ( $1, $2, $3, $4, $5, $6, $7, $8 )
RETURNING id, invoice_number, cashbox_id, currency_id, inventory_id, client_id, amount, discount, net_amount, created_at
`

type CreateSalesInvoiceParams struct {
	CashboxID     int64  `json:"cashboxId"`
	InvoiceNumber string `json:"invoiceNumber"`
	InventoryID   int64  `json:"inventoryId"`
	ClientID      int64  `json:"clientId"`
	Amount        string `json:"amount"`
	NetAmount     string `json:"netAmount"`
	Discount      int16  `json:"discount"`
	CurrencyID    int64  `json:"currencyId"`
}

func (q *Queries) CreateSalesInvoice(ctx context.Context, arg CreateSalesInvoiceParams) (SalesInvoice, error) {
	row := q.db.QueryRowContext(ctx, createSalesInvoice,
		arg.CashboxID,
		arg.InvoiceNumber,
		arg.InventoryID,
		arg.ClientID,
		arg.Amount,
		arg.NetAmount,
		arg.Discount,
		arg.CurrencyID,
	)
	var i SalesInvoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.CashboxID,
		&i.CurrencyID,
		&i.InventoryID,
		&i.ClientID,
		&i.Amount,
		&i.Discount,
		&i.NetAmount,
		&i.CreatedAt,
	)
	return i, err
}

const getReturnInvoice = `-- name: GetReturnInvoice :one
SELECT id, invoice_number, sales_invoice_id, created_at FROM return_invoices
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetReturnInvoice(ctx context.Context, id int64) (ReturnInvoice, error) {
	row := q.db.QueryRowContext(ctx, getReturnInvoice, id)
	var i ReturnInvoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.SalesInvoiceID,
		&i.CreatedAt,
	)
	return i, err
}

const getSalesInvoice = `-- name: GetSalesInvoice :one
SELECT id, invoice_number, cashbox_id, currency_id, inventory_id, client_id, amount, discount, net_amount, created_at FROM sales_invoices
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSalesInvoice(ctx context.Context, id int64) (SalesInvoice, error) {
	row := q.db.QueryRowContext(ctx, getSalesInvoice, id)
	var i SalesInvoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceNumber,
		&i.CashboxID,
		&i.CurrencyID,
		&i.InventoryID,
		&i.ClientID,
		&i.Amount,
		&i.Discount,
		&i.NetAmount,
		&i.CreatedAt,
	)
	return i, err
}

const listSalesInvoices = `-- name: ListSalesInvoices :many
SELECT id, invoice_number, cashbox_id, currency_id, inventory_id, client_id, amount, discount, net_amount, created_at FROM sales_invoices
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListSalesInvoicesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSalesInvoices(ctx context.Context, arg ListSalesInvoicesParams) ([]SalesInvoice, error) {
	rows, err := q.db.QueryContext(ctx, listSalesInvoices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesInvoice{}
	for rows.Next() {
		var i SalesInvoice
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceNumber,
			&i.CashboxID,
			&i.CurrencyID,
			&i.InventoryID,
			&i.ClientID,
			&i.Amount,
			&i.Discount,
			&i.NetAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
