// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoice.sql

package db

import (
	"context"
)

const addSalesInvoiceProduct = `-- name: AddSalesInvoiceProduct :one
INSERT INTO sales_invoice_products (
  invoice_id,
  product_id,
  quantity
) 
VALUES ( $1, $2, $3 )
RETURNING invoice_id, product_id, quantity, created_at
`

type AddSalesInvoiceProductParams struct {
	InvoiceID int64 `json:"invoiceId"`
	ProductID int64 `json:"productId"`
	Quantity  int64 `json:"quantity"`
}

func (q *Queries) AddSalesInvoiceProduct(ctx context.Context, arg AddSalesInvoiceProductParams) (SalesInvoiceProduct, error) {
	row := q.db.QueryRowContext(ctx, addSalesInvoiceProduct, arg.InvoiceID, arg.ProductID, arg.Quantity)
	var i SalesInvoiceProduct
	err := row.Scan(
		&i.InvoiceID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const createReturnInvoice = `-- name: CreateReturnInvoice :one
INSERT INTO return_invoices (
  invoice_index,
  invoice_code,
  cashbox_id,
  sales_invoice_id
) 
VALUES ( $1, $2, $3, $4 )
RETURNING id, invoice_code, invoice_index, year, cashbox_id, sales_invoice_id, created_at
`

type CreateReturnInvoiceParams struct {
	InvoiceIndex   int64  `json:"invoiceIndex"`
	InvoiceCode    string `json:"invoiceCode"`
	CashboxID      int64  `json:"cashboxId"`
	SalesInvoiceID int64  `json:"salesInvoiceId"`
}

func (q *Queries) CreateReturnInvoice(ctx context.Context, arg CreateReturnInvoiceParams) (ReturnInvoice, error) {
	row := q.db.QueryRowContext(ctx, createReturnInvoice,
		arg.InvoiceIndex,
		arg.InvoiceCode,
		arg.CashboxID,
		arg.SalesInvoiceID,
	)
	var i ReturnInvoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceCode,
		&i.InvoiceIndex,
		&i.Year,
		&i.CashboxID,
		&i.SalesInvoiceID,
		&i.CreatedAt,
	)
	return i, err
}

const createSalesInvoice = `-- name: CreateSalesInvoice :one
INSERT INTO sales_invoices (
  cashbox_id,
  invoice_index,
  invoice_code,
  inventory_id,
  year,
  client_id,
  amount,
  net_amount,
  discount,
  currency_code
) 
VALUES ( $1, $2, $3, $4, $5, $6, $7, $8, $9, $10 )
RETURNING id, invoice_code, invoice_index, year, cashbox_id, currency_code, inventory_id, client_id, amount, discount, net_amount, created_at
`

type CreateSalesInvoiceParams struct {
	CashboxID    int64  `json:"cashboxId"`
	InvoiceIndex int64  `json:"invoiceIndex"`
	InvoiceCode  string `json:"invoiceCode"`
	InventoryID  int64  `json:"inventoryId"`
	Year         int32  `json:"year"`
	ClientID     int64  `json:"clientId"`
	Amount       int64  `json:"amount"`
	NetAmount    int64  `json:"netAmount"`
	Discount     int16  `json:"discount"`
	CurrencyCode string `json:"currencyCode"`
}

func (q *Queries) CreateSalesInvoice(ctx context.Context, arg CreateSalesInvoiceParams) (SalesInvoice, error) {
	row := q.db.QueryRowContext(ctx, createSalesInvoice,
		arg.CashboxID,
		arg.InvoiceIndex,
		arg.InvoiceCode,
		arg.InventoryID,
		arg.Year,
		arg.ClientID,
		arg.Amount,
		arg.NetAmount,
		arg.Discount,
		arg.CurrencyCode,
	)
	var i SalesInvoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceCode,
		&i.InvoiceIndex,
		&i.Year,
		&i.CashboxID,
		&i.CurrencyCode,
		&i.InventoryID,
		&i.ClientID,
		&i.Amount,
		&i.Discount,
		&i.NetAmount,
		&i.CreatedAt,
	)
	return i, err
}

const getReturnInvoice = `-- name: GetReturnInvoice :one
SELECT id, invoice_code, invoice_index, year, cashbox_id, sales_invoice_id, created_at FROM return_invoices
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetReturnInvoice(ctx context.Context, id int64) (ReturnInvoice, error) {
	row := q.db.QueryRowContext(ctx, getReturnInvoice, id)
	var i ReturnInvoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceCode,
		&i.InvoiceIndex,
		&i.Year,
		&i.CashboxID,
		&i.SalesInvoiceID,
		&i.CreatedAt,
	)
	return i, err
}

const getSalesInvoice = `-- name: GetSalesInvoice :one
SELECT id, invoice_code, invoice_index, year, cashbox_id, currency_code, inventory_id, client_id, amount, discount, net_amount, created_at FROM sales_invoices
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSalesInvoice(ctx context.Context, id int64) (SalesInvoice, error) {
	row := q.db.QueryRowContext(ctx, getSalesInvoice, id)
	var i SalesInvoice
	err := row.Scan(
		&i.ID,
		&i.InvoiceCode,
		&i.InvoiceIndex,
		&i.Year,
		&i.CashboxID,
		&i.CurrencyCode,
		&i.InventoryID,
		&i.ClientID,
		&i.Amount,
		&i.Discount,
		&i.NetAmount,
		&i.CreatedAt,
	)
	return i, err
}

const listReturnInvoices = `-- name: ListReturnInvoices :many
SELECT id, invoice_code, invoice_index, year, cashbox_id, sales_invoice_id, created_at
FROM return_invoices
ORDER BY created_at
DESC
LIMIT $1
OFFSET $2
`

type ListReturnInvoicesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListReturnInvoices(ctx context.Context, arg ListReturnInvoicesParams) ([]ReturnInvoice, error) {
	rows, err := q.db.QueryContext(ctx, listReturnInvoices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReturnInvoice{}
	for rows.Next() {
		var i ReturnInvoice
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceCode,
			&i.InvoiceIndex,
			&i.Year,
			&i.CashboxID,
			&i.SalesInvoiceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesInvoices = `-- name: ListSalesInvoices :many
SELECT id, invoice_code, invoice_index, year, cashbox_id, currency_code, inventory_id, client_id, amount, discount, net_amount, created_at
FROM sales_invoices
ORDER BY created_at
DESC
LIMIT $1
OFFSET $2
`

type ListSalesInvoicesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSalesInvoices(ctx context.Context, arg ListSalesInvoicesParams) ([]SalesInvoice, error) {
	rows, err := q.db.QueryContext(ctx, listSalesInvoices, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesInvoice{}
	for rows.Next() {
		var i SalesInvoice
		if err := rows.Scan(
			&i.ID,
			&i.InvoiceCode,
			&i.InvoiceIndex,
			&i.Year,
			&i.CashboxID,
			&i.CurrencyCode,
			&i.InventoryID,
			&i.ClientID,
			&i.Amount,
			&i.Discount,
			&i.NetAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextReturnInvoiceIndexIncrement = `-- name: NextReturnInvoiceIndexIncrement :one
INSERT INTO return_invoices_indexes (year, cashbox_id, last_index)
VALUES ($1, $2, 1)
ON CONFLICT (year, cashbox_id)
DO UPDATE SET last_index = return_invoices_indexes.last_index + 1
RETURNING last_index
`

type NextReturnInvoiceIndexIncrementParams struct {
	Year      int32 `json:"year"`
	CashboxID int64 `json:"cashboxId"`
}

func (q *Queries) NextReturnInvoiceIndexIncrement(ctx context.Context, arg NextReturnInvoiceIndexIncrementParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextReturnInvoiceIndexIncrement, arg.Year, arg.CashboxID)
	var last_index int64
	err := row.Scan(&last_index)
	return last_index, err
}

const nextSalesInvoiceIndexIncrement = `-- name: NextSalesInvoiceIndexIncrement :one
INSERT INTO sales_invoices_indexes  (year, cashbox_id, last_index)
VALUES ($1, $2, 1)
ON CONFLICT (year, cashbox_id)
DO UPDATE SET last_index = sales_invoices_indexes.last_index + 1
RETURNING last_index
`

type NextSalesInvoiceIndexIncrementParams struct {
	Year      int32 `json:"year"`
	CashboxID int64 `json:"cashboxId"`
}

func (q *Queries) NextSalesInvoiceIndexIncrement(ctx context.Context, arg NextSalesInvoiceIndexIncrementParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, nextSalesInvoiceIndexIncrement, arg.Year, arg.CashboxID)
	var last_index int64
	err := row.Scan(&last_index)
	return last_index, err
}
