// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type EntryReferenceType string

const (
	EntryReferenceTypeTransfer   EntryReferenceType = "transfer"
	EntryReferenceTypeSale       EntryReferenceType = "sale"
	EntryReferenceTypePurchase   EntryReferenceType = "purchase"
	EntryReferenceTypeAdjustment EntryReferenceType = "adjustment"
)

func (e *EntryReferenceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntryReferenceType(s)
	case string:
		*e = EntryReferenceType(s)
	default:
		return fmt.Errorf("unsupported scan type for EntryReferenceType: %T", src)
	}
	return nil
}

type NullEntryReferenceType struct {
	EntryReferenceType EntryReferenceType `json:"entryReferenceType"`
	Valid              bool               `json:"valid"` // Valid is true if EntryReferenceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntryReferenceType) Scan(value interface{}) error {
	if value == nil {
		ns.EntryReferenceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntryReferenceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntryReferenceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntryReferenceType), nil
}

type OrderType string

const (
	OrderTypeSales  OrderType = "sales"
	OrderTypeReturn OrderType = "return"
)

func (e *OrderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderType(s)
	case string:
		*e = OrderType(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderType: %T", src)
	}
	return nil
}

type NullOrderType struct {
	OrderType OrderType `json:"orderType"`
	Valid     bool      `json:"valid"` // Valid is true if OrderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderType) Scan(value interface{}) error {
	if value == nil {
		ns.OrderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderType), nil
}

type TransferType string

const (
	TransferTypeAssets   TransferType = "assets"
	TransferTypeProducts TransferType = "products"
)

func (e *TransferType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransferType(s)
	case string:
		*e = TransferType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransferType: %T", src)
	}
	return nil
}

type NullTransferType struct {
	TransferType TransferType `json:"transferType"`
	Valid        bool         `json:"valid"` // Valid is true if TransferType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransferType) Scan(value interface{}) error {
	if value == nil {
		ns.TransferType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransferType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransferType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransferType), nil
}

type Asset struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Code      string    `json:"code"`
	TypeID    int64     `json:"typeId"`
	Version   int32     `json:"version"`
	BoughtAt  time.Time `json:"boughtAt"`
	CreatedAt time.Time `json:"createdAt"`
}

type AssetsType struct {
	ID   int64  `json:"id"`
	Type string `json:"type"`
}

type Attribute struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type AttributesValue struct {
	ID          int64  `json:"id"`
	AttributeID int64  `json:"attributeId"`
	Value       string `json:"value"`
}

type Barcode struct {
	Barcode   int64         `json:"barcode"`
	ProductID int64         `json:"productId"`
	ColorID   sql.NullInt64 `json:"colorId"`
	SizeID    sql.NullInt64 `json:"sizeId"`
	Version   int32         `json:"version"`
	CreatedAt time.Time     `json:"createdAt"`
}

type Client struct {
	ID            int64     `json:"id"`
	Name          string    `json:"name"`
	Phone         int64     `json:"phone"`
	LoyaltyPoints int64     `json:"loyaltyPoints"`
	CreatedAt     time.Time `json:"createdAt"`
}

type ClientsDiscount struct {
	ProductID int64     `json:"productId"`
	ClientID  int64     `json:"clientId"`
	Discount  int64     `json:"discount"`
	CreatedAt time.Time `json:"createdAt"`
}

type Color struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	HexValue string `json:"hexValue"`
	Version  int32  `json:"version"`
}

type Currency struct {
	ID         int64  `json:"id"`
	Name       string `json:"name"`
	Code       string `json:"code"`
	ValueInUsd string `json:"valueInUsd"`
}

type Entry struct {
	ID            int64              `json:"id"`
	InventoryID   int64              `json:"inventoryId"`
	ReferenceType EntryReferenceType `json:"referenceType"`
	ReferenceID   int64              `json:"referenceId"`
	ProductID     sql.NullInt64      `json:"productId"`
	AssetID       sql.NullInt64      `json:"assetId"`
	Quantity      int64              `json:"quantity"`
	CreatedAt     time.Time          `json:"createdAt"`
}

type InventoriesAsset struct {
	AssetID     int64 `json:"assetId"`
	InventoryID int64 `json:"inventoryId"`
	Quantity    int64 `json:"quantity"`
}

type InventoriesProduct struct {
	ProductID   int64 `json:"productId"`
	InventoryID int64 `json:"inventoryId"`
	Quantity    int64 `json:"quantity"`
}

type Inventory struct {
	ID        int64           `json:"id"`
	Name      string          `json:"name"`
	Code      string          `json:"code"`
	Longitude sql.NullFloat64 `json:"longitude"`
	Latitude  sql.NullFloat64 `json:"latitude"`
	CreatedAt time.Time       `json:"createdAt"`
}

type Order struct {
	ID        int64     `json:"id"`
	ClientID  int64     `json:"clientId"`
	Type      OrderType `json:"type"`
	Sequence  int64     `json:"sequence"`
	Code      string    `json:"code"`
	Amount    int64     `json:"amount"`
	NetAmount int64     `json:"netAmount"`
	Discount  int64     `json:"discount"`
	CreatedAt time.Time `json:"createdAt"`
}

type OrdersProduct struct {
	OrderID   int64     `json:"orderId"`
	ProductID int64     `json:"productId"`
	Quantity  int64     `json:"quantity"`
	CreatedAt time.Time `json:"createdAt"`
}

type Permission struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
}

type Product struct {
	ID          int64     `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsActive    bool      `json:"isActive"`
	Price       int64     `json:"price"`
	Version     int32     `json:"version"`
	Discount    int64     `json:"discount"`
	CreatedAt   time.Time `json:"createdAt"`
}

type ProductSupplier struct {
	ID         int64 `json:"id"`
	ProductID  int64 `json:"productId"`
	SupplierID int64 `json:"supplierId"`
}

type ProductSupplierCost struct {
	ProductSupplierID int64     `json:"productSupplierId"`
	UnitCost          int64     `json:"unitCost"`
	CurrencyID        int64     `json:"currencyId"`
	CreatedAt         time.Time `json:"createdAt"`
}

type ProductsAttribute struct {
	AttributeID      int64 `json:"attributeId"`
	AttributeValueID int64 `json:"attributeValueId"`
	ProductID        int64 `json:"productId"`
}

type ProductsColor struct {
	ProductID int64 `json:"productId"`
	ColorID   int64 `json:"colorId"`
}

type ProductsSize struct {
	ProductID int64 `json:"productId"`
	SizeID    int64 `json:"sizeId"`
}

type Purchase struct {
	ID          int64     `json:"id"`
	SupplierID  int64     `json:"supplierId"`
	PurchasedAt time.Time `json:"purchasedAt"`
}

type PurchaseItem struct {
	ID         int64         `json:"id"`
	PurchaseID sql.NullInt64 `json:"purchaseId"`
	ProductID  sql.NullInt64 `json:"productId"`
	AssetID    sql.NullInt64 `json:"assetId"`
	Quantity   int64         `json:"quantity"`
	UnitPrice  string        `json:"unitPrice"`
	CurrencyID int64         `json:"currencyId"`
}

type Size struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Type      string    `json:"type"`
	Order     string    `json:"order"`
	Version   int32     `json:"version"`
	CreatedAt time.Time `json:"createdAt"`
}

type Supplier struct {
	ID               int64           `json:"id"`
	Name             string          `json:"name"`
	Phone            string          `json:"phone"`
	Country          string          `json:"country"`
	Address          string          `json:"address"`
	AddressLatitude  sql.NullFloat64 `json:"addressLatitude"`
	AddressLongitude sql.NullFloat64 `json:"addressLongitude"`
	CreatedAt        time.Time       `json:"createdAt"`
}

type Token struct {
	Hash   []byte    `json:"hash"`
	UserID int64     `json:"userId"`
	Expiry time.Time `json:"expiry"`
	Scope  string    `json:"scope"`
}

type Transfer struct {
	ID              int64        `json:"id"`
	FromInventoryID int64        `json:"fromInventoryId"`
	ToInventoryID   int64        `json:"toInventoryId"`
	Type            TransferType `json:"type"`
	CreatedAt       time.Time    `json:"createdAt"`
}

// Each row references either a product or an asset. Never both.
type TransferItem struct {
	ID         int64         `json:"id"`
	TransferID int64         `json:"transferId"`
	ProductID  sql.NullInt64 `json:"productId"`
	AssetID    sql.NullInt64 `json:"assetId"`
	Quantity   int64         `json:"quantity"`
}

type User struct {
	ID           int64     `json:"id"`
	CreatedAt    time.Time `json:"createdAt"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash []byte    `json:"passwordHash"`
	Activated    bool      `json:"activated"`
	Version      int32     `json:"version"`
}

type UsersPermission struct {
	UserID       int64 `json:"userId"`
	PermissionID int64 `json:"permissionId"`
}
