// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"
)

type Asset struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Code      string    `json:"code"`
	TypeID    int64     `json:"typeId"`
	Version   int32     `json:"version"`
	BoughtAt  time.Time `json:"boughtAt"`
	CreatedAt time.Time `json:"createdAt"`
}

type AssetsType struct {
	ID   int64  `json:"id"`
	Type string `json:"type"`
}

type Atransfer struct {
	ID              int64     `json:"id"`
	FromInventoryID int64     `json:"fromInventoryId"`
	ToInventoryID   int64     `json:"toInventoryId"`
	CreatedAt       time.Time `json:"createdAt"`
}

type AtransfersAsset struct {
	AtransferID int64 `json:"atransferId"`
	AssetID     int64 `json:"assetId"`
	Quantity    int64 `json:"quantity"`
}

type Barcode struct {
	Barcode   int64         `json:"barcode"`
	ProductID int64         `json:"productId"`
	ColorID   sql.NullInt64 `json:"colorId"`
	SizeID    sql.NullInt64 `json:"sizeId"`
	Version   int32         `json:"version"`
	CreatedAt time.Time     `json:"createdAt"`
}

type Brand struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Version int32  `json:"version"`
}

type Category struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Version int32  `json:"version"`
}

type Client struct {
	ID            int64     `json:"id"`
	Name          string    `json:"name"`
	Phone         int64     `json:"phone"`
	LoyaltyPoints int64     `json:"loyaltyPoints"`
	CreatedAt     time.Time `json:"createdAt"`
}

type ClientsDiscount struct {
	ProductID int64     `json:"productId"`
	ClientID  int64     `json:"clientId"`
	Discount  int64     `json:"discount"`
	CreatedAt time.Time `json:"createdAt"`
}

type Color struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	HexValue string `json:"hexValue"`
	Version  int32  `json:"version"`
}

type InventoriesAsset struct {
	AssetID     int64 `json:"assetId"`
	InventoryID int64 `json:"inventoryId"`
	Quantity    int64 `json:"quantity"`
}

type InventoriesProduct struct {
	ProductID   int64 `json:"productId"`
	InventoryID int64 `json:"inventoryId"`
	Quantity    int64 `json:"quantity"`
}

type Inventory struct {
	ID        int64           `json:"id"`
	Name      string          `json:"name"`
	Code      string          `json:"code"`
	Longitude sql.NullFloat64 `json:"longitude"`
	Latitude  sql.NullFloat64 `json:"latitude"`
	CreatedAt time.Time       `json:"createdAt"`
}

type Kind struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Version int32  `json:"version"`
}

type Order struct {
	ID        int64     `json:"id"`
	TypeID    int64     `json:"typeId"`
	Sequence  int64     `json:"sequence"`
	Code      string    `json:"code"`
	Amount    int64     `json:"amount"`
	NetAmount int64     `json:"netAmount"`
	Discount  int64     `json:"discount"`
	CreatedAt time.Time `json:"createdAt"`
}

type OrdersProduct struct {
	OrderID   int64     `json:"orderId"`
	ProductID int64     `json:"productId"`
	Quantity  int64     `json:"quantity"`
	CreatedAt time.Time `json:"createdAt"`
}

type Orderstype struct {
	ID   int64  `json:"id"`
	Type string `json:"type"`
	Code string `json:"code"`
}

type Origin struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Version int32  `json:"version"`
}

type Permission struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
}

type Product struct {
	ID            int64     `json:"id"`
	Code          string    `json:"code"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	KindID        int64     `json:"kindId"`
	IsActive      bool      `json:"isActive"`
	CategoryID    int64     `json:"categoryId"`
	SubcategoryID int64     `json:"subcategoryId"`
	UnitID        int64     `json:"unitId"`
	TypeID        int64     `json:"typeId"`
	Year          int32     `json:"year"`
	SeasonID      int64     `json:"seasonId"`
	BrandID       int64     `json:"brandId"`
	OriginID      int64     `json:"originId"`
	Price         int32     `json:"price"`
	Version       int32     `json:"version"`
	Discount      int64     `json:"discount"`
	CreatedAt     time.Time `json:"createdAt"`
}

type ProductsColor struct {
	ProductID int64 `json:"productId"`
	ColorID   int64 `json:"colorId"`
}

type ProductsSize struct {
	ProductID int64 `json:"productId"`
	SizeID    int64 `json:"sizeId"`
}

type ProductsSupplier struct {
	ProductID   int64 `json:"productId"`
	SupplierID  int64 `json:"supplierId"`
	ProductCost int64 `json:"productCost"`
}

type Ptransfer struct {
	ID              int64     `json:"id"`
	FromInventoryID int64     `json:"fromInventoryId"`
	ToInventoryID   int64     `json:"toInventoryId"`
	CreatedAt       time.Time `json:"createdAt"`
}

type PtransfersProduct struct {
	PtransferID int64 `json:"ptransferId"`
	ProductID   int64 `json:"productId"`
	Quantity    int64 `json:"quantity"`
}

type Season struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Version int32  `json:"version"`
}

type Size struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Type      string    `json:"type"`
	Order     string    `json:"order"`
	Version   int32     `json:"version"`
	CreatedAt time.Time `json:"createdAt"`
}

type Subcategory struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Version int32  `json:"version"`
}

type Supplier struct {
	ID        int64         `json:"id"`
	Name      string        `json:"name"`
	Phone     string        `json:"phone"`
	ProductID int64         `json:"productId"`
	ColorID   sql.NullInt64 `json:"colorId"`
	SizeID    sql.NullInt64 `json:"sizeId"`
	CreatedAt time.Time     `json:"createdAt"`
}

type Token struct {
	Hash   []byte    `json:"hash"`
	UserID int64     `json:"userId"`
	Expiry time.Time `json:"expiry"`
	Scope  string    `json:"scope"`
}

type Type struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Version int32  `json:"version"`
}

type Unit struct {
	ID      int64  `json:"id"`
	Name    string `json:"name"`
	Version int32  `json:"version"`
}

type User struct {
	ID           int64     `json:"id"`
	CreatedAt    time.Time `json:"createdAt"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	PasswordHash []byte    `json:"passwordHash"`
	Activated    bool      `json:"activated"`
	Version      int32     `json:"version"`
}

type UsersPermission struct {
	UserID       int64 `json:"userId"`
	PermissionID int64 `json:"permissionId"`
}
