// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"database/sql/driver"
	"fmt"
	"time"
)

type CouponStatus string

const (
	CouponStatusActive   CouponStatus = "active"
	CouponStatusInactive CouponStatus = "inactive"
)

func (e *CouponStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CouponStatus(s)
	case string:
		*e = CouponStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CouponStatus: %T", src)
	}
	return nil
}

type NullCouponStatus struct {
	CouponStatus CouponStatus `json:"couponStatus"`
	Valid        bool         `json:"valid"` // Valid is true if CouponStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCouponStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CouponStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CouponStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCouponStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CouponStatus), nil
}

type DiscountType string

const (
	DiscountTypeFixed      DiscountType = "fixed"
	DiscountTypePercentage DiscountType = "percentage"
)

func (e *DiscountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DiscountType(s)
	case string:
		*e = DiscountType(s)
	default:
		return fmt.Errorf("unsupported scan type for DiscountType: %T", src)
	}
	return nil
}

type NullDiscountType struct {
	DiscountType DiscountType `json:"discountType"`
	Valid        bool         `json:"valid"` // Valid is true if DiscountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDiscountType) Scan(value interface{}) error {
	if value == nil {
		ns.DiscountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DiscountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDiscountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DiscountType), nil
}

type EntryReferenceType string

const (
	EntryReferenceTypeSalesInvoice  EntryReferenceType = "sales_invoice"
	EntryReferenceTypeReturnInvoice EntryReferenceType = "return_invoice"
	EntryReferenceTypeExpense       EntryReferenceType = "expense"
	EntryReferenceTypePurchase      EntryReferenceType = "purchase"
)

func (e *EntryReferenceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EntryReferenceType(s)
	case string:
		*e = EntryReferenceType(s)
	default:
		return fmt.Errorf("unsupported scan type for EntryReferenceType: %T", src)
	}
	return nil
}

type NullEntryReferenceType struct {
	EntryReferenceType EntryReferenceType `json:"entryReferenceType"`
	Valid              bool               `json:"valid"` // Valid is true if EntryReferenceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEntryReferenceType) Scan(value interface{}) error {
	if value == nil {
		ns.EntryReferenceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EntryReferenceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEntryReferenceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EntryReferenceType), nil
}

type TransferType string

const (
	TransferTypeAssets   TransferType = "assets"
	TransferTypeProducts TransferType = "products"
)

func (e *TransferType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransferType(s)
	case string:
		*e = TransferType(s)
	default:
		return fmt.Errorf("unsupported scan type for TransferType: %T", src)
	}
	return nil
}

type NullTransferType struct {
	TransferType TransferType `json:"transferType"`
	Valid        bool         `json:"valid"` // Valid is true if TransferType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransferType) Scan(value interface{}) error {
	if value == nil {
		ns.TransferType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransferType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransferType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransferType), nil
}

type Asset struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Code      string    `json:"code"`
	TypeID    int64     `json:"typeId"`
	Version   int32     `json:"version"`
	BoughtAt  time.Time `json:"boughtAt"`
	CreatedAt time.Time `json:"createdAt"`
}

type AssetsType struct {
	ID   int64  `json:"id"`
	Type string `json:"type"`
}

type Attribute struct {
	Name string `json:"name"`
}

type AttributesValue struct {
	ID        int64  `json:"id"`
	Attribute string `json:"attribute"`
	Value     string `json:"value"`
}

type Barcode struct {
	Barcode   int64         `json:"barcode"`
	ProductID int64         `json:"productId"`
	ColorID   sql.NullInt64 `json:"colorId"`
	SizeID    sql.NullInt64 `json:"sizeId"`
	Version   int32         `json:"version"`
	CreatedAt time.Time     `json:"createdAt"`
}

type Cashbox struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Code      string    `json:"code"`
	IsActive  bool      `json:"isActive"`
	CreatedAt time.Time `json:"createdAt"`
}

type CashboxAccount struct {
	ID             int64  `json:"id"`
	Type           string `json:"type"`
	ShiftID        int64  `json:"shiftId"`
	CurrencyCode   string `json:"currencyCode"`
	OpeningBalance int64  `json:"openingBalance"`
	Balance        int64  `json:"balance"`
}

type Client struct {
	ID                 int64     `json:"id"`
	Name               string    `json:"name"`
	Phone              string    `json:"phone"`
	TotalLoyaltyPoints int64     `json:"totalLoyaltyPoints"`
	ValidLoyaltyPoints int64     `json:"validLoyaltyPoints"`
	CreatedAt          time.Time `json:"createdAt"`
}

type Color struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	HexValue string `json:"hexValue"`
	Version  int32  `json:"version"`
}

type Coupon struct {
	Code         string       `json:"code"`
	Status       CouponStatus `json:"status"`
	DiscountType DiscountType `json:"discountType"`
	Reason       string       `json:"reason"`
	ClientID     int64        `json:"clientId"`
	ValidUntil   time.Time    `json:"validUntil"`
	CreatedAt    time.Time    `json:"createdAt"`
}

type Currency struct {
	Code                   string `json:"code"`
	Name                   string `json:"name"`
	Symbol                 string `json:"symbol"`
	IsDefault              bool   `json:"isDefault"`
	ValueInDefaultCurrency int64  `json:"valueInDefaultCurrency"`
}

type Entry struct {
	ID                         int64              `json:"id"`
	CashboxID                  int64              `json:"cashboxId"`
	InventoryID                int64              `json:"inventoryId"`
	ReferenceType              EntryReferenceType `json:"referenceType"`
	ReferenceID                int64              `json:"referenceId"`
	NetAmountInDefaultCurrency int64              `json:"netAmountInDefaultCurrency"`
	CreatedAt                  time.Time          `json:"createdAt"`
}

type Expense struct {
	ID           int64     `json:"id"`
	Description  string    `json:"description"`
	Amount       int64     `json:"amount"`
	CurrencyCode string    `json:"currencyCode"`
	CreatedAt    time.Time `json:"createdAt"`
}

type InventoriesAsset struct {
	AssetID     int64 `json:"assetId"`
	InventoryID int64 `json:"inventoryId"`
	Quantity    int64 `json:"quantity"`
}

type InventoriesProduct struct {
	ProductID   int64 `json:"productId"`
	InventoryID int64 `json:"inventoryId"`
	Quantity    int64 `json:"quantity"`
}

type Inventory struct {
	ID        int64           `json:"id"`
	Name      string          `json:"name"`
	Code      string          `json:"code"`
	Longitude sql.NullFloat64 `json:"longitude"`
	Latitude  sql.NullFloat64 `json:"latitude"`
	CreatedAt time.Time       `json:"createdAt"`
}

type Permission struct {
	ID   int64  `json:"id"`
	Code string `json:"code"`
}

type Product struct {
	ID          int64     `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsActive    bool      `json:"isActive"`
	Price       int64     `json:"price"`
	Version     int32     `json:"version"`
	Discount    int64     `json:"discount"`
	CreatedAt   time.Time `json:"createdAt"`
}

type ProductSupplier struct {
	ID         int64 `json:"id"`
	ProductID  int64 `json:"productId"`
	SupplierID int64 `json:"supplierId"`
}

type ProductSupplierCost struct {
	ProductSupplierID int64     `json:"productSupplierId"`
	UnitCost          int64     `json:"unitCost"`
	CurrencyCode      string    `json:"currencyCode"`
	CreatedAt         time.Time `json:"createdAt"`
}

type ProductsAttribute struct {
	Attribute        string `json:"attribute"`
	AttributeValueID int64  `json:"attributeValueId"`
	ProductID        int64  `json:"productId"`
}

type ProductsColor struct {
	ProductID int64 `json:"productId"`
	ColorID   int64 `json:"colorId"`
}

type ProductsSize struct {
	ProductID int64 `json:"productId"`
	SizeID    int64 `json:"sizeId"`
}

type Purchase struct {
	ID          int64     `json:"id"`
	SupplierID  int64     `json:"supplierId"`
	PurchasedAt time.Time `json:"purchasedAt"`
}

type PurchaseItem struct {
	ID           int64         `json:"id"`
	PurchaseID   sql.NullInt64 `json:"purchaseId"`
	ProductID    sql.NullInt64 `json:"productId"`
	AssetID      sql.NullInt64 `json:"assetId"`
	Quantity     int64         `json:"quantity"`
	UnitPrice    int64         `json:"unitPrice"`
	CurrencyCode string        `json:"currencyCode"`
}

type ReturnInvoice struct {
	ID             int64     `json:"id"`
	InvoiceCode    string    `json:"invoiceCode"`
	InvoiceIndex   int64     `json:"invoiceIndex"`
	Year           int32     `json:"year"`
	CashboxID      int64     `json:"cashboxId"`
	SalesInvoiceID int64     `json:"salesInvoiceId"`
	CreatedAt      time.Time `json:"createdAt"`
}

type ReturnInvoicesIndex struct {
	Year      int32 `json:"year"`
	CashboxID int64 `json:"cashboxId"`
	LastIndex int64 `json:"lastIndex"`
}

type SalesInvoice struct {
	ID           int64     `json:"id"`
	InvoiceCode  string    `json:"invoiceCode"`
	InvoiceIndex int64     `json:"invoiceIndex"`
	Year         int32     `json:"year"`
	CashboxID    int64     `json:"cashboxId"`
	CurrencyCode string    `json:"currencyCode"`
	InventoryID  int64     `json:"inventoryId"`
	ClientID     int64     `json:"clientId"`
	Amount       int64     `json:"amount"`
	Discount     int16     `json:"discount"`
	NetAmount    int64     `json:"netAmount"`
	CreatedAt    time.Time `json:"createdAt"`
}

type SalesInvoiceProduct struct {
	InvoiceID int64     `json:"invoiceId"`
	ProductID int64     `json:"productId"`
	Quantity  int64     `json:"quantity"`
	CreatedAt time.Time `json:"createdAt"`
}

type SalesInvoicesIndex struct {
	Year      int32 `json:"year"`
	CashboxID int64 `json:"cashboxId"`
	LastIndex int64 `json:"lastIndex"`
}

type Shift struct {
	ID                  int64        `json:"id"`
	IsClosed            bool         `json:"isClosed"`
	CashboxID           int64        `json:"cashboxId"`
	TotalOpeningBalance int64        `json:"totalOpeningBalance"`
	TotalBalance        int64        `json:"totalBalance"`
	OpeningDateTime     time.Time    `json:"openingDateTime"`
	ClosingDateTime     sql.NullTime `json:"closingDateTime"`
}

type Size struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Type      string    `json:"type"`
	Order     string    `json:"order"`
	Version   int32     `json:"version"`
	CreatedAt time.Time `json:"createdAt"`
}

type Supplier struct {
	ID               int64           `json:"id"`
	Name             string          `json:"name"`
	Phone            string          `json:"phone"`
	Country          string          `json:"country"`
	Address          string          `json:"address"`
	AddressLatitude  sql.NullFloat64 `json:"addressLatitude"`
	AddressLongitude sql.NullFloat64 `json:"addressLongitude"`
	CreatedAt        time.Time       `json:"createdAt"`
}

type Token struct {
	Hash   []byte    `json:"hash"`
	UserID int64     `json:"userId"`
	Expiry time.Time `json:"expiry"`
	Scope  string    `json:"scope"`
}

type Transfer struct {
	ID              int64        `json:"id"`
	FromInventoryID int64        `json:"fromInventoryId"`
	ToInventoryID   int64        `json:"toInventoryId"`
	Type            TransferType `json:"type"`
	CreatedAt       time.Time    `json:"createdAt"`
}

// Each row references either a product or an asset. Never both.
type TransferItem struct {
	ID         int64         `json:"id"`
	TransferID int64         `json:"transferId"`
	ProductID  sql.NullInt64 `json:"productId"`
	AssetID    sql.NullInt64 `json:"assetId"`
	Quantity   int64         `json:"quantity"`
}

type User struct {
	ID                int64     `json:"id"`
	Name              string    `json:"name"`
	Email             string    `json:"email"`
	PasswordHash      []byte    `json:"passwordHash"`
	PasswordChangedAt time.Time `json:"passwordChangedAt"`
	Activated         bool      `json:"activated"`
	Version           int32     `json:"version"`
	CreatedAt         time.Time `json:"createdAt"`
}

type UsersPermission struct {
	UserID       int64 `json:"userId"`
	PermissionID int64 `json:"permissionId"`
}
