// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: order.sql

package db

import (
	"context"
)

const addOrderProduct = `-- name: AddOrderProduct :one
INSERT INTO orders_products (
  order_id,
  product_id,
  quantity
) 
VALUES ( $1, $2, $3 )
RETURNING order_id, product_id, quantity, created_at
`

type AddOrderProductParams struct {
	OrderID   int64 `json:"orderId"`
	ProductID int64 `json:"productId"`
	Quantity  int64 `json:"quantity"`
}

func (q *Queries) AddOrderProduct(ctx context.Context, arg AddOrderProductParams) (OrdersProduct, error) {
	row := q.db.QueryRowContext(ctx, addOrderProduct, arg.OrderID, arg.ProductID, arg.Quantity)
	var i OrdersProduct
	err := row.Scan(
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (
  type_id,
  sequence
) 
VALUES ( $1, $2 )
RETURNING id, type_id, sequence, code, amount, net_amount, discount, created_at
`

type CreateOrderParams struct {
	TypeID   int64 `json:"typeId"`
	Sequence int64 `json:"sequence"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRowContext(ctx, createOrder, arg.TypeID, arg.Sequence)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TypeID,
		&i.Sequence,
		&i.Code,
		&i.Amount,
		&i.NetAmount,
		&i.Discount,
		&i.CreatedAt,
	)
	return i, err
}

const getOrder = `-- name: GetOrder :one
SELECT id, type_id, sequence, code, amount, net_amount, discount, created_at FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRowContext(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.TypeID,
		&i.Sequence,
		&i.Code,
		&i.Amount,
		&i.NetAmount,
		&i.Discount,
		&i.CreatedAt,
	)
	return i, err
}

const listOrders = `-- name: ListOrders :many
SELECT id, type_id, sequence, code, amount, net_amount, discount, created_at FROM orders
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListOrdersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListOrders(ctx context.Context, arg ListOrdersParams) ([]Order, error) {
	rows, err := q.db.QueryContext(ctx, listOrders, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.TypeID,
			&i.Sequence,
			&i.Code,
			&i.Amount,
			&i.NetAmount,
			&i.Discount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
