// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_attributes.sql

package db

import (
	"context"
)

const createProductAttribute = `-- name: CreateProductAttribute :one
INSERT INTO products_attributes (
  product_id,
  attribute_id,
  attribute_value_id
) VALUES (
    $1, $2, $3
) RETURNING attribute_id, attribute_value_id, product_id
`

type CreateProductAttributeParams struct {
	ProductID        int64 `json:"productId"`
	AttributeID      int64 `json:"attributeId"`
	AttributeValueID int64 `json:"attributeValueId"`
}

func (q *Queries) CreateProductAttribute(ctx context.Context, arg CreateProductAttributeParams) (ProductsAttribute, error) {
	row := q.db.QueryRowContext(ctx, createProductAttribute, arg.ProductID, arg.AttributeID, arg.AttributeValueID)
	var i ProductsAttribute
	err := row.Scan(&i.AttributeID, &i.AttributeValueID, &i.ProductID)
	return i, err
}

const getProductAttributeValue = `-- name: GetProductAttributeValue :one
SELECT attribute_id, attribute_value_id, product_id FROM products_attributes
WHERE product_id = $1 AND attribute_id = $2
`

type GetProductAttributeValueParams struct {
	ProductID   int64 `json:"productId"`
	AttributeID int64 `json:"attributeId"`
}

func (q *Queries) GetProductAttributeValue(ctx context.Context, arg GetProductAttributeValueParams) (ProductsAttribute, error) {
	row := q.db.QueryRowContext(ctx, getProductAttributeValue, arg.ProductID, arg.AttributeID)
	var i ProductsAttribute
	err := row.Scan(&i.AttributeID, &i.AttributeValueID, &i.ProductID)
	return i, err
}

const listProductAttributes = `-- name: ListProductAttributes :many
SELECT p.id, av.id, av.attribute_id, av.value
FROM products p
INNER JOIN attributes_values av
ON p.id = av.product_id
ORDER BY value
LIMIT $1
OFFSET $2
`

type ListProductAttributesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListProductAttributesRow struct {
	ID          int64  `json:"id"`
	ID_2        int64  `json:"id2"`
	AttributeID int64  `json:"attributeId"`
	Value       string `json:"value"`
}

func (q *Queries) ListProductAttributes(ctx context.Context, arg ListProductAttributesParams) ([]ListProductAttributesRow, error) {
	rows, err := q.db.QueryContext(ctx, listProductAttributes, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductAttributesRow
	for rows.Next() {
		var i ListProductAttributesRow
		if err := rows.Scan(
			&i.ID,
			&i.ID_2,
			&i.AttributeID,
			&i.Value,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductAttribute = `-- name: UpdateProductAttribute :exec
UPDATE products_attributes 
SET attribute_value_id = $2
WHERE product_id = $1 AND attribute_id = $2
`

type UpdateProductAttributeParams struct {
	ProductID        int64 `json:"productId"`
	AttributeValueID int64 `json:"attributeValueId"`
}

func (q *Queries) UpdateProductAttribute(ctx context.Context, arg UpdateProductAttributeParams) error {
	_, err := q.db.ExecContext(ctx, updateProductAttribute, arg.ProductID, arg.AttributeValueID)
	return err
}
