// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package db

import (
	"context"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
  name,
  kind_id,
  category_id,
  subcategory_id,
  unit_id,
  type_id,
  year,
  season_id,
  brand_id,
  origin_id,
  price 
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, code, name, description, kind_id, is_active, category_id, subcategory_id, unit_id, type_id, year, season_id, brand_id, origin_id, price, version, discount, created_at
`

type CreateProductParams struct {
	Name          string `json:"name"`
	KindID        int64  `json:"kindId"`
	CategoryID    int64  `json:"categoryId"`
	SubcategoryID int64  `json:"subcategoryId"`
	UnitID        int64  `json:"unitId"`
	TypeID        int64  `json:"typeId"`
	Year          int32  `json:"year"`
	SeasonID      int64  `json:"seasonId"`
	BrandID       int64  `json:"brandId"`
	OriginID      int64  `json:"originId"`
	Price         int32  `json:"price"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRowContext(ctx, createProduct,
		arg.Name,
		arg.KindID,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.UnitID,
		arg.TypeID,
		arg.Year,
		arg.SeasonID,
		arg.BrandID,
		arg.OriginID,
		arg.Price,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.KindID,
		&i.IsActive,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.UnitID,
		&i.TypeID,
		&i.Year,
		&i.SeasonID,
		&i.BrandID,
		&i.OriginID,
		&i.Price,
		&i.Version,
		&i.Discount,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, code, name, description, kind_id, is_active, category_id, subcategory_id, unit_id, type_id, year, season_id, brand_id, origin_id, price, version, discount, created_at FROM products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id int64) (Product, error) {
	row := q.db.QueryRowContext(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.KindID,
		&i.IsActive,
		&i.CategoryID,
		&i.SubcategoryID,
		&i.UnitID,
		&i.TypeID,
		&i.Year,
		&i.SeasonID,
		&i.BrandID,
		&i.OriginID,
		&i.Price,
		&i.Version,
		&i.Discount,
		&i.CreatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, code, name, description, kind_id, is_active, category_id, subcategory_id, unit_id, type_id, year, season_id, brand_id, origin_id, price, version, discount, created_at FROM products
ORDER BY name
LIMIT $1
OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.QueryContext(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.KindID,
			&i.IsActive,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.UnitID,
			&i.TypeID,
			&i.Year,
			&i.SeasonID,
			&i.BrandID,
			&i.OriginID,
			&i.Price,
			&i.Version,
			&i.Discount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :exec
UPDATE products 
  SET name = $2,
  kind_id = $3,
  category_id = $4,
  subcategory_id = $5,
  unit_id = $6,
  type_id = $7,
  year = $8,
  season_id = $9,
  brand_id = $10,
  origin_id = $11,
  price = $12
WHERE id = $1
`

type UpdateProductParams struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	KindID        int64  `json:"kindId"`
	CategoryID    int64  `json:"categoryId"`
	SubcategoryID int64  `json:"subcategoryId"`
	UnitID        int64  `json:"unitId"`
	TypeID        int64  `json:"typeId"`
	Year          int32  `json:"year"`
	SeasonID      int64  `json:"seasonId"`
	BrandID       int64  `json:"brandId"`
	OriginID      int64  `json:"originId"`
	Price         int32  `json:"price"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) error {
	_, err := q.db.ExecContext(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.KindID,
		arg.CategoryID,
		arg.SubcategoryID,
		arg.UnitID,
		arg.TypeID,
		arg.Year,
		arg.SeasonID,
		arg.BrandID,
		arg.OriginID,
		arg.Price,
	)
	return err
}
