// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: purchase.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const addPurchaseItem = `-- name: AddPurchaseItem :one
INSERT INTO purchase_items (
  purchase_id,
  product_id,
  asset_id,
  quantity,
  unit_price
) 
VALUES ( $1, $2, $3, $4, $5 )
RETURNING id, purchase_id, product_id, asset_id, quantity, unit_price
`

type AddPurchaseItemParams struct {
	PurchaseID sql.NullInt64 `json:"purchaseId"`
	ProductID  sql.NullInt64 `json:"productId"`
	AssetID    sql.NullInt64 `json:"assetId"`
	Quantity   int64         `json:"quantity"`
	UnitPrice  string        `json:"unitPrice"`
}

func (q *Queries) AddPurchaseItem(ctx context.Context, arg AddPurchaseItemParams) (PurchaseItem, error) {
	row := q.db.QueryRowContext(ctx, addPurchaseItem,
		arg.PurchaseID,
		arg.ProductID,
		arg.AssetID,
		arg.Quantity,
		arg.UnitPrice,
	)
	var i PurchaseItem
	err := row.Scan(
		&i.ID,
		&i.PurchaseID,
		&i.ProductID,
		&i.AssetID,
		&i.Quantity,
		&i.UnitPrice,
	)
	return i, err
}

const createPurchase = `-- name: CreatePurchase :one
INSERT INTO purchases (
  supplier_id,
  purchased_at
) 
VALUES ( $1, $2 )
RETURNING id, supplier_id, purchased_at
`

type CreatePurchaseParams struct {
	SupplierID  int64     `json:"supplierId"`
	PurchasedAt time.Time `json:"purchasedAt"`
}

func (q *Queries) CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (Purchase, error) {
	row := q.db.QueryRowContext(ctx, createPurchase, arg.SupplierID, arg.PurchasedAt)
	var i Purchase
	err := row.Scan(&i.ID, &i.SupplierID, &i.PurchasedAt)
	return i, err
}

const deletePurchaseItem = `-- name: DeletePurchaseItem :exec
delete from purchase_items
where id = $1 
  and product_id = $2 
  and asset_id = $3
`

type DeletePurchaseItemParams struct {
	ID        int64         `json:"id"`
	ProductID sql.NullInt64 `json:"productId"`
	AssetID   sql.NullInt64 `json:"assetId"`
}

func (q *Queries) DeletePurchaseItem(ctx context.Context, arg DeletePurchaseItemParams) error {
	_, err := q.db.ExecContext(ctx, deletePurchaseItem, arg.ID, arg.ProductID, arg.AssetID)
	return err
}

const getPurchase = `-- name: GetPurchase :one
SELECT id, supplier_id, purchased_at FROM purchases
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPurchase(ctx context.Context, id int64) (Purchase, error) {
	row := q.db.QueryRowContext(ctx, getPurchase, id)
	var i Purchase
	err := row.Scan(&i.ID, &i.SupplierID, &i.PurchasedAt)
	return i, err
}

const listPurchases = `-- name: ListPurchases :many
SELECT id, supplier_id, purchased_at FROM purchases
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListPurchasesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPurchases(ctx context.Context, arg ListPurchasesParams) ([]Purchase, error) {
	rows, err := q.db.QueryContext(ctx, listPurchases, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Purchase{}
	for rows.Next() {
		var i Purchase
		if err := rows.Scan(&i.ID, &i.SupplierID, &i.PurchasedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
