// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (CashboxAccount, error)
	AddInventoryProduct(ctx context.Context, arg AddInventoryProductParams) (InventoriesProduct, error)
	AddPurchaseItem(ctx context.Context, arg AddPurchaseItemParams) (PurchaseItem, error)
	AddSalesInvoiceProduct(ctx context.Context, arg AddSalesInvoiceProductParams) (SalesInvoiceProduct, error)
	AddSupplierProduct(ctx context.Context, arg AddSupplierProductParams) (ProductSupplier, error)
	AddSupplierProductCost(ctx context.Context, arg AddSupplierProductCostParams) (ProductSupplierCost, error)
	AddToShiftBalance(ctx context.Context, arg AddToShiftBalanceParams) (Shift, error)
	CloseShift(ctx context.Context, arg CloseShiftParams) error
	CreateAttributeValue(ctx context.Context, arg CreateAttributeValueParams) (AttributesValue, error)
	CreateCashbox(ctx context.Context, arg CreateCashboxParams) (Cashbox, error)
	CreateCashboxAccount(ctx context.Context, arg CreateCashboxAccountParams) (CashboxAccount, error)
	CreateClient(ctx context.Context, arg CreateClientParams) (Client, error)
	CreateCoupon(ctx context.Context, arg CreateCouponParams) (Coupon, error)
	CreateCurrency(ctx context.Context, arg CreateCurrencyParams) (Currency, error)
	CreateEntryItem(ctx context.Context, arg CreateEntryItemParams) (Entry, error)
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	CreateInventory(ctx context.Context, arg CreateInventoryParams) (Inventory, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductAttribute(ctx context.Context, arg CreateProductAttributeParams) (ProductsAttribute, error)
	CreatePurchase(ctx context.Context, arg CreatePurchaseParams) (Purchase, error)
	CreateReturnInvoice(ctx context.Context, arg CreateReturnInvoiceParams) (ReturnInvoice, error)
	CreateSalesInvoice(ctx context.Context, arg CreateSalesInvoiceParams) (SalesInvoice, error)
	CreateShift(ctx context.Context, arg CreateShiftParams) (Shift, error)
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error)
	CreateTransferItem(ctx context.Context, arg CreateTransferItemParams) (TransferItem, error)
	DeleteClient(ctx context.Context, id int64) error
	DeleteCurrency(ctx context.Context, code string) error
	DeleteInventory(ctx context.Context, id int64) error
	DeleteInventoryProduct(ctx context.Context, arg DeleteInventoryProductParams) error
	DeleteProduct(ctx context.Context, id int64) error
	DeleteSupplierProduct(ctx context.Context, id int64) error
	GetAttributeValue(ctx context.Context, id int64) (AttributesValue, error)
	GetCashbox(ctx context.Context, id int64) (Cashbox, error)
	GetCashboxAccount(ctx context.Context, id int64) (CashboxAccount, error)
	GetClient(ctx context.Context, id int64) (Client, error)
	GetCoupon(ctx context.Context, code string) (Coupon, error)
	GetCurrency(ctx context.Context, code string) (Currency, error)
	GetDefaultCurrency(ctx context.Context) (Currency, error)
	GetEntry(ctx context.Context, id int64) (Entry, error)
	GetExpense(ctx context.Context, id int64) (Expense, error)
	GetInventory(ctx context.Context, id int64) (Inventory, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetProductAttributeValue(ctx context.Context, arg GetProductAttributeValueParams) (ProductsAttribute, error)
	GetPurchase(ctx context.Context, id int64) (Purchase, error)
	GetReturnInvoice(ctx context.Context, id int64) (ReturnInvoice, error)
	GetSalesInvoice(ctx context.Context, id int64) (SalesInvoice, error)
	GetShift(ctx context.Context, id int64) (Shift, error)
	GetSupplier(ctx context.Context, id int64) (Supplier, error)
	GetTransfer(ctx context.Context, id int64) (Transfer, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]CashboxAccount, error)
	ListAttributeValues(ctx context.Context, arg ListAttributeValuesParams) ([]ListAttributeValuesRow, error)
	ListCashboxes(ctx context.Context, arg ListCashboxesParams) ([]Cashbox, error)
	ListClients(ctx context.Context, arg ListClientsParams) ([]Client, error)
	ListCoupons(ctx context.Context, arg ListCouponsParams) ([]Coupon, error)
	ListCurrencies(ctx context.Context, arg ListCurrenciesParams) ([]Currency, error)
	ListEntries(ctx context.Context, arg ListEntriesParams) ([]Entry, error)
	ListExpenses(ctx context.Context, arg ListExpensesParams) ([]Expense, error)
	ListInventories(ctx context.Context, arg ListInventoriesParams) ([]Inventory, error)
	ListInventoryProducts(ctx context.Context, inventoryID int64) ([]ListInventoryProductsRow, error)
	ListProductAttributes(ctx context.Context, arg ListProductAttributesParams) ([]ProductsAttribute, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListPurchases(ctx context.Context, arg ListPurchasesParams) ([]Purchase, error)
	ListSalesInvoices(ctx context.Context, arg ListSalesInvoicesParams) ([]SalesInvoice, error)
	ListShifts(ctx context.Context, arg ListShiftsParams) ([]Shift, error)
	ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error)
	// TODO maybe this is not so clean
	ListTransferItems(ctx context.Context, transferID int64) ([]ListTransferItemsRow, error)
	ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error)
	NextReturnInvoiceIndexIncrement(ctx context.Context, arg NextReturnInvoiceIndexIncrementParams) (int64, error)
	NextSalesInvoiceIndexIncrement(ctx context.Context, arg NextSalesInvoiceIndexIncrementParams) (int64, error)
	UpdateAttributeValue(ctx context.Context, arg UpdateAttributeValueParams) error
	UpdateClient(ctx context.Context, arg UpdateClientParams) error
	UpdateClientLoyaltyPoints(ctx context.Context, arg UpdateClientLoyaltyPointsParams) error
	UpdateCouponStatus(ctx context.Context, arg UpdateCouponStatusParams) error
	UpdateInventory(ctx context.Context, arg UpdateInventoryParams) error
	UpdateInventoryProduct(ctx context.Context, arg UpdateInventoryProductParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) error
	UpdateProductAttribute(ctx context.Context, arg UpdateProductAttributeParams) error
	UpdateTransfer(ctx context.Context, arg UpdateTransferParams) error
}

var _ Querier = (*Queries)(nil)
