// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shift.sql

package db

import (
	"context"
	"database/sql"
)

const addAccountBalance = `-- name: AddAccountBalance :one
UPDATE cashbox_accounts
SET balance = balance + $1
WHERE id = $2
RETURNING id, type, shift_id, currency_code, opening_balance, balance
`

type AddAccountBalanceParams struct {
	Amount int64 `json:"amount"`
	ID     int64 `json:"id"`
}

func (q *Queries) AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (CashboxAccount, error) {
	row := q.db.QueryRowContext(ctx, addAccountBalance, arg.Amount, arg.ID)
	var i CashboxAccount
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ShiftID,
		&i.CurrencyCode,
		&i.OpeningBalance,
		&i.Balance,
	)
	return i, err
}

const addToShiftBalance = `-- name: AddToShiftBalance :one
UPDATE shifts 
  SET total_balance = total_balance + $1
WHERE id = $2
RETURNING id, is_closed, cashbox_id, total_opening_balance, total_balance, opening_date_time, closing_date_time
`

type AddToShiftBalanceParams struct {
	Amount int64 `json:"amount"`
	ID     int64 `json:"id"`
}

func (q *Queries) AddToShiftBalance(ctx context.Context, arg AddToShiftBalanceParams) (Shift, error) {
	row := q.db.QueryRowContext(ctx, addToShiftBalance, arg.Amount, arg.ID)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.IsClosed,
		&i.CashboxID,
		&i.TotalOpeningBalance,
		&i.TotalBalance,
		&i.OpeningDateTime,
		&i.ClosingDateTime,
	)
	return i, err
}

const closeShift = `-- name: CloseShift :exec
UPDATE shifts 
  SET closing_date_time = $1,
  is_closed = $2
WHERE id = $3
`

type CloseShiftParams struct {
	ClosingDateTime sql.NullTime `json:"closingDateTime"`
	IsClosed        bool         `json:"isClosed"`
	ID              int64        `json:"id"`
}

func (q *Queries) CloseShift(ctx context.Context, arg CloseShiftParams) error {
	_, err := q.db.ExecContext(ctx, closeShift, arg.ClosingDateTime, arg.IsClosed, arg.ID)
	return err
}

const createCashboxAccount = `-- name: CreateCashboxAccount :one
INSERT INTO cashbox_accounts (
  type,
  shift_id,
  currency_code,
  opening_balance,
  balance
) 
VALUES ($1, $2, $3, $4, $5)
RETURNING id, type, shift_id, currency_code, opening_balance, balance
`

type CreateCashboxAccountParams struct {
	Type           string `json:"type"`
	ShiftID        int64  `json:"shiftId"`
	CurrencyCode   string `json:"currencyCode"`
	OpeningBalance int64  `json:"openingBalance"`
	Balance        int64  `json:"balance"`
}

func (q *Queries) CreateCashboxAccount(ctx context.Context, arg CreateCashboxAccountParams) (CashboxAccount, error) {
	row := q.db.QueryRowContext(ctx, createCashboxAccount,
		arg.Type,
		arg.ShiftID,
		arg.CurrencyCode,
		arg.OpeningBalance,
		arg.Balance,
	)
	var i CashboxAccount
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ShiftID,
		&i.CurrencyCode,
		&i.OpeningBalance,
		&i.Balance,
	)
	return i, err
}

const createShift = `-- name: CreateShift :one
INSERT INTO shifts (
  cashbox_id,
  total_opening_balance,
  total_balance
) 
VALUES ( $1, $2, $3 )
RETURNING id, is_closed, cashbox_id, total_opening_balance, total_balance, opening_date_time, closing_date_time
`

type CreateShiftParams struct {
	CashboxID           int64 `json:"cashboxId"`
	TotalOpeningBalance int64 `json:"totalOpeningBalance"`
	TotalBalance        int64 `json:"totalBalance"`
}

func (q *Queries) CreateShift(ctx context.Context, arg CreateShiftParams) (Shift, error) {
	row := q.db.QueryRowContext(ctx, createShift, arg.CashboxID, arg.TotalOpeningBalance, arg.TotalBalance)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.IsClosed,
		&i.CashboxID,
		&i.TotalOpeningBalance,
		&i.TotalBalance,
		&i.OpeningDateTime,
		&i.ClosingDateTime,
	)
	return i, err
}

const getCashboxAccount = `-- name: GetCashboxAccount :one
SELECT id, type, shift_id, currency_code, opening_balance, balance FROM cashbox_accounts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetCashboxAccount(ctx context.Context, id int64) (CashboxAccount, error) {
	row := q.db.QueryRowContext(ctx, getCashboxAccount, id)
	var i CashboxAccount
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ShiftID,
		&i.CurrencyCode,
		&i.OpeningBalance,
		&i.Balance,
	)
	return i, err
}

const getShift = `-- name: GetShift :one
SELECT id, is_closed, cashbox_id, total_opening_balance, total_balance, opening_date_time, closing_date_time FROM shifts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetShift(ctx context.Context, id int64) (Shift, error) {
	row := q.db.QueryRowContext(ctx, getShift, id)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.IsClosed,
		&i.CashboxID,
		&i.TotalOpeningBalance,
		&i.TotalBalance,
		&i.OpeningDateTime,
		&i.ClosingDateTime,
	)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id, type, shift_id, currency_code, opening_balance, balance FROM cashbox_accounts
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListAccountsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListAccounts(ctx context.Context, arg ListAccountsParams) ([]CashboxAccount, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CashboxAccount{}
	for rows.Next() {
		var i CashboxAccount
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ShiftID,
			&i.CurrencyCode,
			&i.OpeningBalance,
			&i.Balance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShifts = `-- name: ListShifts :many
SELECT id, is_closed, cashbox_id, total_opening_balance, total_balance, opening_date_time, closing_date_time FROM shifts
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListShiftsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListShifts(ctx context.Context, arg ListShiftsParams) ([]Shift, error) {
	rows, err := q.db.QueryContext(ctx, listShifts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shift{}
	for rows.Next() {
		var i Shift
		if err := rows.Scan(
			&i.ID,
			&i.IsClosed,
			&i.CashboxID,
			&i.TotalOpeningBalance,
			&i.TotalBalance,
			&i.OpeningDateTime,
			&i.ClosingDateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
