// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shift.sql

package db

import (
	"context"
	"database/sql"
)

const createShift = `-- name: CreateShift :one
INSERT INTO shifts (
  opening_balance,
  current_balance
) 
VALUES ( $1, $2 )
RETURNING id, opening_balance, current_balance, opening_date_time, closing_date_time
`

type CreateShiftParams struct {
	OpeningBalance string `json:"openingBalance"`
	CurrentBalance string `json:"currentBalance"`
}

func (q *Queries) CreateShift(ctx context.Context, arg CreateShiftParams) (Shift, error) {
	row := q.db.QueryRowContext(ctx, createShift, arg.OpeningBalance, arg.CurrentBalance)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.OpeningBalance,
		&i.CurrentBalance,
		&i.OpeningDateTime,
		&i.ClosingDateTime,
	)
	return i, err
}

const setShiftCloseingTime = `-- name: SetShiftCloseingTime :exec
UPDATE shifts 
  SET closing_date_time = $1
WHERE id = $1
`

func (q *Queries) SetShiftCloseingTime(ctx context.Context, closingDateTime sql.NullTime) error {
	_, err := q.db.ExecContext(ctx, setShiftCloseingTime, closingDateTime)
	return err
}
