// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shift.sql

package db

import (
	"context"
	"database/sql"
)

const addToShiftBalance = `-- name: AddToShiftBalance :one
UPDATE shifts 
  SET total_balance = total_balance + $1
WHERE id = $2
RETURNING id, is_closed, cashbox_id, total_opening_balance, total_balance, opening_date_time, closing_date_time
`

type AddToShiftBalanceParams struct {
	Amount int64 `json:"amount"`
	ID     int64 `json:"id"`
}

func (q *Queries) AddToShiftBalance(ctx context.Context, arg AddToShiftBalanceParams) (Shift, error) {
	row := q.db.QueryRowContext(ctx, addToShiftBalance, arg.Amount, arg.ID)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.IsClosed,
		&i.CashboxID,
		&i.TotalOpeningBalance,
		&i.TotalBalance,
		&i.OpeningDateTime,
		&i.ClosingDateTime,
	)
	return i, err
}

const closeShift = `-- name: CloseShift :exec
UPDATE shifts 
  SET closing_date_time = $1,
  is_closed = $2
WHERE id = $3
`

type CloseShiftParams struct {
	ClosingDateTime sql.NullTime `json:"closingDateTime"`
	IsClosed        bool         `json:"isClosed"`
	ID              int64        `json:"id"`
}

func (q *Queries) CloseShift(ctx context.Context, arg CloseShiftParams) error {
	_, err := q.db.ExecContext(ctx, closeShift, arg.ClosingDateTime, arg.IsClosed, arg.ID)
	return err
}

const createShift = `-- name: CreateShift :one
INSERT INTO shifts (
  cashbox_id,
  total_opening_balance,
  total_balance
) 
VALUES ( $1, $2, $3 )
RETURNING id, is_closed, cashbox_id, total_opening_balance, total_balance, opening_date_time, closing_date_time
`

type CreateShiftParams struct {
	CashboxID           int64 `json:"cashboxId"`
	TotalOpeningBalance int64 `json:"totalOpeningBalance"`
	TotalBalance        int64 `json:"totalBalance"`
}

func (q *Queries) CreateShift(ctx context.Context, arg CreateShiftParams) (Shift, error) {
	row := q.db.QueryRowContext(ctx, createShift, arg.CashboxID, arg.TotalOpeningBalance, arg.TotalBalance)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.IsClosed,
		&i.CashboxID,
		&i.TotalOpeningBalance,
		&i.TotalBalance,
		&i.OpeningDateTime,
		&i.ClosingDateTime,
	)
	return i, err
}

const getShift = `-- name: GetShift :one
SELECT id, is_closed, cashbox_id, total_opening_balance, total_balance, opening_date_time, closing_date_time FROM shifts
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetShift(ctx context.Context, id int64) (Shift, error) {
	row := q.db.QueryRowContext(ctx, getShift, id)
	var i Shift
	err := row.Scan(
		&i.ID,
		&i.IsClosed,
		&i.CashboxID,
		&i.TotalOpeningBalance,
		&i.TotalBalance,
		&i.OpeningDateTime,
		&i.ClosingDateTime,
	)
	return i, err
}

const listShifts = `-- name: ListShifts :many
SELECT id, is_closed, cashbox_id, total_opening_balance, total_balance, opening_date_time, closing_date_time FROM shifts
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListShiftsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListShifts(ctx context.Context, arg ListShiftsParams) ([]Shift, error) {
	rows, err := q.db.QueryContext(ctx, listShifts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Shift{}
	for rows.Next() {
		var i Shift
		if err := rows.Scan(
			&i.ID,
			&i.IsClosed,
			&i.CashboxID,
			&i.TotalOpeningBalance,
			&i.TotalBalance,
			&i.OpeningDateTime,
			&i.ClosingDateTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
