// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: supplier.sql

package db

import (
	"context"
	"database/sql"
)

const addSupplierProduct = `-- name: AddSupplierProduct :one
INSERT INTO product_suppliers (
  product_id,
  supplier_id
) 
VALUES ( $1, $2 )
RETURNING id, product_id, supplier_id
`

type AddSupplierProductParams struct {
	ProductID  int64 `json:"productId"`
	SupplierID int64 `json:"supplierId"`
}

func (q *Queries) AddSupplierProduct(ctx context.Context, arg AddSupplierProductParams) (ProductSupplier, error) {
	row := q.db.QueryRowContext(ctx, addSupplierProduct, arg.ProductID, arg.SupplierID)
	var i ProductSupplier
	err := row.Scan(&i.ID, &i.ProductID, &i.SupplierID)
	return i, err
}

const addSupplierProductCost = `-- name: AddSupplierProductCost :one
INSERT INTO product_supplier_costs (
  product_supplier_id,
  unit_cost,
  currency_id
) 
VALUES ( $1, $2, $3 )
RETURNING product_supplier_id, unit_cost, currency_id, created_at
`

type AddSupplierProductCostParams struct {
	ProductSupplierID int64 `json:"productSupplierId"`
	UnitCost          int64 `json:"unitCost"`
	CurrencyID        int64 `json:"currencyId"`
}

func (q *Queries) AddSupplierProductCost(ctx context.Context, arg AddSupplierProductCostParams) (ProductSupplierCost, error) {
	row := q.db.QueryRowContext(ctx, addSupplierProductCost, arg.ProductSupplierID, arg.UnitCost, arg.CurrencyID)
	var i ProductSupplierCost
	err := row.Scan(
		&i.ProductSupplierID,
		&i.UnitCost,
		&i.CurrencyID,
		&i.CreatedAt,
	)
	return i, err
}

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (
  name,
  phone,
  country,
  address,
  address_latitude,
  address_longitude
) 
VALUES ( $1, $2, $3, $4, $5, $6 )
RETURNING id, name, phone, country, address, address_latitude, address_longitude, created_at
`

type CreateSupplierParams struct {
	Name             string          `json:"name"`
	Phone            string          `json:"phone"`
	Country          string          `json:"country"`
	Address          string          `json:"address"`
	AddressLatitude  sql.NullFloat64 `json:"addressLatitude"`
	AddressLongitude sql.NullFloat64 `json:"addressLongitude"`
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRowContext(ctx, createSupplier,
		arg.Name,
		arg.Phone,
		arg.Country,
		arg.Address,
		arg.AddressLatitude,
		arg.AddressLongitude,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Country,
		&i.Address,
		&i.AddressLatitude,
		&i.AddressLongitude,
		&i.CreatedAt,
	)
	return i, err
}

const deleteSupplierProduct = `-- name: DeleteSupplierProduct :exec
delete from product_suppliers
where id = $1
`

func (q *Queries) DeleteSupplierProduct(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSupplierProduct, id)
	return err
}

const getSupplier = `-- name: GetSupplier :one
SELECT id, name, phone, country, address, address_latitude, address_longitude, created_at FROM suppliers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetSupplier(ctx context.Context, id int64) (Supplier, error) {
	row := q.db.QueryRowContext(ctx, getSupplier, id)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.Country,
		&i.Address,
		&i.AddressLatitude,
		&i.AddressLongitude,
		&i.CreatedAt,
	)
	return i, err
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, name, phone, country, address, address_latitude, address_longitude, created_at FROM suppliers
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListSuppliersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error) {
	rows, err := q.db.QueryContext(ctx, listSuppliers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Supplier{}
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.Country,
			&i.Address,
			&i.AddressLatitude,
			&i.AddressLongitude,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
