// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfer.sql

package db

import (
	"context"
)

const createATransfer = `-- name: CreateATransfer :one
INSERT INTO atransfers (
  from_inventory_id,
  to_inventory_id
) VALUES ( $1, $2 )
RETURNING id, from_inventory_id, to_inventory_id, created_at
`

type CreateATransferParams struct {
	FromInventoryID int64 `json:"fromInventoryId"`
	ToInventoryID   int64 `json:"toInventoryId"`
}

func (q *Queries) CreateATransfer(ctx context.Context, arg CreateATransferParams) (Atransfer, error) {
	row := q.db.QueryRowContext(ctx, createATransfer, arg.FromInventoryID, arg.ToInventoryID)
	var i Atransfer
	err := row.Scan(
		&i.ID,
		&i.FromInventoryID,
		&i.ToInventoryID,
		&i.CreatedAt,
	)
	return i, err
}

const createPTransfer = `-- name: CreatePTransfer :one
INSERT INTO ptransfers (
  from_inventory_id,
  to_inventory_id
) VALUES ( $1, $2 )
RETURNING id, from_inventory_id, to_inventory_id, created_at
`

type CreatePTransferParams struct {
	FromInventoryID int64 `json:"fromInventoryId"`
	ToInventoryID   int64 `json:"toInventoryId"`
}

func (q *Queries) CreatePTransfer(ctx context.Context, arg CreatePTransferParams) (Ptransfer, error) {
	row := q.db.QueryRowContext(ctx, createPTransfer, arg.FromInventoryID, arg.ToInventoryID)
	var i Ptransfer
	err := row.Scan(
		&i.ID,
		&i.FromInventoryID,
		&i.ToInventoryID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteATransfer = `-- name: DeleteATransfer :exec
DELETE FROM atransfers
WHERE id = $1
`

func (q *Queries) DeleteATransfer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteATransfer, id)
	return err
}

const deletePTransfer = `-- name: DeletePTransfer :exec
DELETE FROM ptransfers
WHERE id = $1
`

func (q *Queries) DeletePTransfer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePTransfer, id)
	return err
}

const getATransfer = `-- name: GetATransfer :one
SELECT id, from_inventory_id, to_inventory_id, created_at FROM atransfers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetATransfer(ctx context.Context, id int64) (Atransfer, error) {
	row := q.db.QueryRowContext(ctx, getATransfer, id)
	var i Atransfer
	err := row.Scan(
		&i.ID,
		&i.FromInventoryID,
		&i.ToInventoryID,
		&i.CreatedAt,
	)
	return i, err
}

const getPTransfer = `-- name: GetPTransfer :one
SELECT id, from_inventory_id, to_inventory_id, created_at FROM ptransfers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPTransfer(ctx context.Context, id int64) (Ptransfer, error) {
	row := q.db.QueryRowContext(ctx, getPTransfer, id)
	var i Ptransfer
	err := row.Scan(
		&i.ID,
		&i.FromInventoryID,
		&i.ToInventoryID,
		&i.CreatedAt,
	)
	return i, err
}

const listATransfers = `-- name: ListATransfers :many
SELECT id, from_inventory_id, to_inventory_id, created_at FROM atransfers
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListATransfersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListATransfers(ctx context.Context, arg ListATransfersParams) ([]Atransfer, error) {
	rows, err := q.db.QueryContext(ctx, listATransfers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Atransfer
	for rows.Next() {
		var i Atransfer
		if err := rows.Scan(
			&i.ID,
			&i.FromInventoryID,
			&i.ToInventoryID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPTransfers = `-- name: ListPTransfers :many
SELECT id, from_inventory_id, to_inventory_id, created_at FROM ptransfers
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListPTransfersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPTransfers(ctx context.Context, arg ListPTransfersParams) ([]Ptransfer, error) {
	rows, err := q.db.QueryContext(ctx, listPTransfers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ptransfer
	for rows.Next() {
		var i Ptransfer
		if err := rows.Scan(
			&i.ID,
			&i.FromInventoryID,
			&i.ToInventoryID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
