// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfer_assets.sql

package db

import (
	"context"
	"time"
)

const createATransfer = `-- name: CreateATransfer :one
INSERT INTO atransfers (
  from_inventory_id,
  to_inventory_id
) VALUES ( $1, $2 )
RETURNING id, from_inventory_id, to_inventory_id, created_at
`

type CreateATransferParams struct {
	FromInventoryID int64 `json:"fromInventoryId"`
	ToInventoryID   int64 `json:"toInventoryId"`
}

func (q *Queries) CreateATransfer(ctx context.Context, arg CreateATransferParams) (Atransfer, error) {
	row := q.db.QueryRowContext(ctx, createATransfer, arg.FromInventoryID, arg.ToInventoryID)
	var i Atransfer
	err := row.Scan(
		&i.ID,
		&i.FromInventoryID,
		&i.ToInventoryID,
		&i.CreatedAt,
	)
	return i, err
}

const createATransferAsset = `-- name: CreateATransferAsset :one
INSERT INTO atransfers_assets (
  transfer_id,
  asset_id
) VALUES ( $1, $2 )
RETURNING transfer_id, asset_id, quantity
`

type CreateATransferAssetParams struct {
	TransferID int64 `json:"transferId"`
	AssetID    int64 `json:"assetId"`
}

func (q *Queries) CreateATransferAsset(ctx context.Context, arg CreateATransferAssetParams) (AtransfersAsset, error) {
	row := q.db.QueryRowContext(ctx, createATransferAsset, arg.TransferID, arg.AssetID)
	var i AtransfersAsset
	err := row.Scan(&i.TransferID, &i.AssetID, &i.Quantity)
	return i, err
}

const deleteATransfer = `-- name: DeleteATransfer :exec
DELETE FROM atransfers
WHERE id = $1
`

func (q *Queries) DeleteATransfer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteATransfer, id)
	return err
}

const getATransfer = `-- name: GetATransfer :one
SELECT id, from_inventory_id, to_inventory_id, created_at FROM atransfers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetATransfer(ctx context.Context, id int64) (Atransfer, error) {
	row := q.db.QueryRowContext(ctx, getATransfer, id)
	var i Atransfer
	err := row.Scan(
		&i.ID,
		&i.FromInventoryID,
		&i.ToInventoryID,
		&i.CreatedAt,
	)
	return i, err
}

const listATransferAssets = `-- name: ListATransferAssets :many

SELECT transfer_id, asset_id, quantity, id, name, code, type_id, version, bought_at, created_at FROM atransfers_assets t
INNER JOIN assets p
ON t.asset_id = p.id
WHERE t.transfer_id = $1
`

type ListATransferAssetsRow struct {
	TransferID int64     `json:"transferId"`
	AssetID    int64     `json:"assetId"`
	Quantity   int64     `json:"quantity"`
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	Code       string    `json:"code"`
	TypeID     int64     `json:"typeId"`
	Version    int32     `json:"version"`
	BoughtAt   time.Time `json:"boughtAt"`
	CreatedAt  time.Time `json:"createdAt"`
}

// -----------------------------------
func (q *Queries) ListATransferAssets(ctx context.Context, transferID int64) ([]ListATransferAssetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listATransferAssets, transferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListATransferAssetsRow
	for rows.Next() {
		var i ListATransferAssetsRow
		if err := rows.Scan(
			&i.TransferID,
			&i.AssetID,
			&i.Quantity,
			&i.ID,
			&i.Name,
			&i.Code,
			&i.TypeID,
			&i.Version,
			&i.BoughtAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listATransfers = `-- name: ListATransfers :many
SELECT id, from_inventory_id, to_inventory_id, created_at FROM atransfers
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListATransfersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListATransfers(ctx context.Context, arg ListATransfersParams) ([]Atransfer, error) {
	rows, err := q.db.QueryContext(ctx, listATransfers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Atransfer
	for rows.Next() {
		var i Atransfer
		if err := rows.Scan(
			&i.ID,
			&i.FromInventoryID,
			&i.ToInventoryID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateATransfer = `-- name: UpdateATransfer :exec
UPDATE atransfers 
SET from_inventory_id = $1,
to_inventory_id = $2
WHERE id = $1
`

type UpdateATransferParams struct {
	FromInventoryID int64 `json:"fromInventoryId"`
	ToInventoryID   int64 `json:"toInventoryId"`
}

func (q *Queries) UpdateATransfer(ctx context.Context, arg UpdateATransferParams) error {
	_, err := q.db.ExecContext(ctx, updateATransfer, arg.FromInventoryID, arg.ToInventoryID)
	return err
}
