// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfer.sql

package db

import (
	"context"
	"time"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (
  from_inventory_id,
  to_inventory_id,
  type
) VALUES ( $1, $2, $3 )
RETURNING id, from_inventory_id, to_inventory_id, type, created_at
`

type CreateTransferParams struct {
	FromInventoryID int64        `json:"fromInventoryId"`
	ToInventoryID   int64        `json:"toInventoryId"`
	Type            TransferType `json:"type"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, createTransfer, arg.FromInventoryID, arg.ToInventoryID, arg.Type)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromInventoryID,
		&i.ToInventoryID,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const createTransferAsset = `-- name: CreateTransferAsset :one
INSERT INTO transfers_assets (
  transfer_id,
  asset_id,
  quantity
) VALUES ( $1, $2, $3 )
RETURNING transfer_id, asset_id, quantity
`

type CreateTransferAssetParams struct {
	TransferID int64 `json:"transferId"`
	AssetID    int64 `json:"assetId"`
	Quantity   int64 `json:"quantity"`
}

func (q *Queries) CreateTransferAsset(ctx context.Context, arg CreateTransferAssetParams) (TransfersAsset, error) {
	row := q.db.QueryRowContext(ctx, createTransferAsset, arg.TransferID, arg.AssetID, arg.Quantity)
	var i TransfersAsset
	err := row.Scan(&i.TransferID, &i.AssetID, &i.Quantity)
	return i, err
}

const createTransferProduct = `-- name: CreateTransferProduct :one
INSERT INTO transfers_products (
  transfer_id,
  product_id,
  quantity
) VALUES ( $1, $2, $3 )
RETURNING transfer_id, product_id, quantity
`

type CreateTransferProductParams struct {
	TransferID int64 `json:"transferId"`
	ProductID  int64 `json:"productId"`
	Quantity   int64 `json:"quantity"`
}

func (q *Queries) CreateTransferProduct(ctx context.Context, arg CreateTransferProductParams) (TransfersProduct, error) {
	row := q.db.QueryRowContext(ctx, createTransferProduct, arg.TransferID, arg.ProductID, arg.Quantity)
	var i TransfersProduct
	err := row.Scan(&i.TransferID, &i.ProductID, &i.Quantity)
	return i, err
}

const getTransfer = `-- name: GetTransfer :one
SELECT id, from_inventory_id, to_inventory_id, type, created_at FROM transfers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTransfer(ctx context.Context, id int64) (Transfer, error) {
	row := q.db.QueryRowContext(ctx, getTransfer, id)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromInventoryID,
		&i.ToInventoryID,
		&i.Type,
		&i.CreatedAt,
	)
	return i, err
}

const listTransferAssets = `-- name: ListTransferAssets :many
SELECT transfer_id, asset_id, quantity, id, name, code, type_id, version, bought_at, created_at FROM transfers_assets t
INNER JOIN assets a
ON t.asset_id = a.id
WHERE t.transfer_id = $1
`

type ListTransferAssetsRow struct {
	TransferID int64     `json:"transferId"`
	AssetID    int64     `json:"assetId"`
	Quantity   int64     `json:"quantity"`
	ID         int64     `json:"id"`
	Name       string    `json:"name"`
	Code       string    `json:"code"`
	TypeID     int64     `json:"typeId"`
	Version    int32     `json:"version"`
	BoughtAt   time.Time `json:"boughtAt"`
	CreatedAt  time.Time `json:"createdAt"`
}

func (q *Queries) ListTransferAssets(ctx context.Context, transferID int64) ([]ListTransferAssetsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransferAssets, transferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransferAssetsRow{}
	for rows.Next() {
		var i ListTransferAssetsRow
		if err := rows.Scan(
			&i.TransferID,
			&i.AssetID,
			&i.Quantity,
			&i.ID,
			&i.Name,
			&i.Code,
			&i.TypeID,
			&i.Version,
			&i.BoughtAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransferProducts = `-- name: ListTransferProducts :many
SELECT transfer_id, product_id, quantity, id, code, name, description, is_active, price, version, discount, created_at FROM transfers_products t
INNER JOIN products p
ON t.product_id = p.id
WHERE t.transfer_id = $1
`

type ListTransferProductsRow struct {
	TransferID  int64     `json:"transferId"`
	ProductID   int64     `json:"productId"`
	Quantity    int64     `json:"quantity"`
	ID          int64     `json:"id"`
	Code        string    `json:"code"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	IsActive    bool      `json:"isActive"`
	Price       int64     `json:"price"`
	Version     int32     `json:"version"`
	Discount    int64     `json:"discount"`
	CreatedAt   time.Time `json:"createdAt"`
}

func (q *Queries) ListTransferProducts(ctx context.Context, transferID int64) ([]ListTransferProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransferProducts, transferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransferProductsRow{}
	for rows.Next() {
		var i ListTransferProductsRow
		if err := rows.Scan(
			&i.TransferID,
			&i.ProductID,
			&i.Quantity,
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.IsActive,
			&i.Price,
			&i.Version,
			&i.Discount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfers = `-- name: ListTransfers :many
SELECT id, from_inventory_id, to_inventory_id, type, created_at FROM transfers
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListTransfersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListTransfers(ctx context.Context, arg ListTransfersParams) ([]Transfer, error) {
	rows, err := q.db.QueryContext(ctx, listTransfers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transfer{}
	for rows.Next() {
		var i Transfer
		if err := rows.Scan(
			&i.ID,
			&i.FromInventoryID,
			&i.ToInventoryID,
			&i.Type,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransfer = `-- name: UpdateTransfer :exec
UPDATE transfers 
SET from_inventory_id = $2,
to_inventory_id = $3,
type = $4
WHERE id = $1
`

type UpdateTransferParams struct {
	ID              int64        `json:"id"`
	FromInventoryID int64        `json:"fromInventoryId"`
	ToInventoryID   int64        `json:"toInventoryId"`
	Type            TransferType `json:"type"`
}

func (q *Queries) UpdateTransfer(ctx context.Context, arg UpdateTransferParams) error {
	_, err := q.db.ExecContext(ctx, updateTransfer,
		arg.ID,
		arg.FromInventoryID,
		arg.ToInventoryID,
		arg.Type,
	)
	return err
}
