// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfer_products.sql

package db

import (
	"context"
	"time"
)

const createPTransfer = `-- name: CreatePTransfer :one
INSERT INTO ptransfers (
  from_inventory_id,
  to_inventory_id
) VALUES ( $1, $2 )
RETURNING id, from_inventory_id, to_inventory_id, created_at
`

type CreatePTransferParams struct {
	FromInventoryID int64 `json:"fromInventoryId"`
	ToInventoryID   int64 `json:"toInventoryId"`
}

func (q *Queries) CreatePTransfer(ctx context.Context, arg CreatePTransferParams) (Ptransfer, error) {
	row := q.db.QueryRowContext(ctx, createPTransfer, arg.FromInventoryID, arg.ToInventoryID)
	var i Ptransfer
	err := row.Scan(
		&i.ID,
		&i.FromInventoryID,
		&i.ToInventoryID,
		&i.CreatedAt,
	)
	return i, err
}

const createPTransferProduct = `-- name: CreatePTransferProduct :one
INSERT INTO ptransfers_products (
  transfer_id,
  product_id,
  quantity
) VALUES ( $1, $2, $3 )
RETURNING transfer_id, product_id, quantity
`

type CreatePTransferProductParams struct {
	TransferID int64 `json:"transferId"`
	ProductID  int64 `json:"productId"`
	Quantity   int64 `json:"quantity"`
}

func (q *Queries) CreatePTransferProduct(ctx context.Context, arg CreatePTransferProductParams) (PtransfersProduct, error) {
	row := q.db.QueryRowContext(ctx, createPTransferProduct, arg.TransferID, arg.ProductID, arg.Quantity)
	var i PtransfersProduct
	err := row.Scan(&i.TransferID, &i.ProductID, &i.Quantity)
	return i, err
}

const deletePTransfer = `-- name: DeletePTransfer :exec
DELETE FROM ptransfers
WHERE id = $1
`

func (q *Queries) DeletePTransfer(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePTransfer, id)
	return err
}

const getPTransfer = `-- name: GetPTransfer :one
SELECT id, from_inventory_id, to_inventory_id, created_at FROM ptransfers
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPTransfer(ctx context.Context, id int64) (Ptransfer, error) {
	row := q.db.QueryRowContext(ctx, getPTransfer, id)
	var i Ptransfer
	err := row.Scan(
		&i.ID,
		&i.FromInventoryID,
		&i.ToInventoryID,
		&i.CreatedAt,
	)
	return i, err
}

const listPTransferProducts = `-- name: ListPTransferProducts :many

SELECT t.transfer_id, t.product_id, t.quantity, p.id, p.code, p.name, p.description, p.kind_id, p.is_active, p.category_id, p.subcategory_id, p.unit_id, p.type_id, p.year, p.season_id, p.brand_id, p.origin_id, p.price, p.version, p.discount, p.created_at
FROM ptransfers_products t
INNER JOIN products p
ON t.product_id = p.id
WHERE t.transfer_id = $1
`

type ListPTransferProductsRow struct {
	TransferID    int64     `json:"transferId"`
	ProductID     int64     `json:"productId"`
	Quantity      int64     `json:"quantity"`
	ID            int64     `json:"id"`
	Code          string    `json:"code"`
	Name          string    `json:"name"`
	Description   string    `json:"description"`
	KindID        int64     `json:"kindId"`
	IsActive      bool      `json:"isActive"`
	CategoryID    int64     `json:"categoryId"`
	SubcategoryID int64     `json:"subcategoryId"`
	UnitID        int64     `json:"unitId"`
	TypeID        int64     `json:"typeId"`
	Year          int64     `json:"year"`
	SeasonID      int64     `json:"seasonId"`
	BrandID       int64     `json:"brandId"`
	OriginID      int64     `json:"originId"`
	Price         int64     `json:"price"`
	Version       int32     `json:"version"`
	Discount      int64     `json:"discount"`
	CreatedAt     time.Time `json:"createdAt"`
}

// -----------------------------------
func (q *Queries) ListPTransferProducts(ctx context.Context, transferID int64) ([]ListPTransferProductsRow, error) {
	rows, err := q.db.QueryContext(ctx, listPTransferProducts, transferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPTransferProductsRow
	for rows.Next() {
		var i ListPTransferProductsRow
		if err := rows.Scan(
			&i.TransferID,
			&i.ProductID,
			&i.Quantity,
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Description,
			&i.KindID,
			&i.IsActive,
			&i.CategoryID,
			&i.SubcategoryID,
			&i.UnitID,
			&i.TypeID,
			&i.Year,
			&i.SeasonID,
			&i.BrandID,
			&i.OriginID,
			&i.Price,
			&i.Version,
			&i.Discount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPTransfers = `-- name: ListPTransfers :many
SELECT id, from_inventory_id, to_inventory_id, created_at FROM ptransfers
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListPTransfersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListPTransfers(ctx context.Context, arg ListPTransfersParams) ([]Ptransfer, error) {
	rows, err := q.db.QueryContext(ctx, listPTransfers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ptransfer
	for rows.Next() {
		var i Ptransfer
		if err := rows.Scan(
			&i.ID,
			&i.FromInventoryID,
			&i.ToInventoryID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePTransfer = `-- name: UpdatePTransfer :exec
UPDATE ptransfers 
SET from_inventory_id = $1,
to_inventory_id = $2
WHERE id = $1
`

type UpdatePTransferParams struct {
	FromInventoryID int64 `json:"fromInventoryId"`
	ToInventoryID   int64 `json:"toInventoryId"`
}

func (q *Queries) UpdatePTransfer(ctx context.Context, arg UpdatePTransferParams) error {
	_, err := q.db.ExecContext(ctx, updatePTransfer, arg.FromInventoryID, arg.ToInventoryID)
	return err
}
