// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mhdna/kashi/db/sqlc (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	db "github.com/mhdna/kashi/db/sqlc"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddInventoryProduct mocks base method.
func (m *MockStore) AddInventoryProduct(arg0 context.Context, arg1 db.AddInventoryProductParams) (db.InventoriesProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddInventoryProduct", arg0, arg1)
	ret0, _ := ret[0].(db.InventoriesProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddInventoryProduct indicates an expected call of AddInventoryProduct.
func (mr *MockStoreMockRecorder) AddInventoryProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInventoryProduct", reflect.TypeOf((*MockStore)(nil).AddInventoryProduct), arg0, arg1)
}

// AddOrderProduct mocks base method.
func (m *MockStore) AddOrderProduct(arg0 context.Context, arg1 db.AddOrderProductParams) (db.OrdersProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrderProduct", arg0, arg1)
	ret0, _ := ret[0].(db.OrdersProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddOrderProduct indicates an expected call of AddOrderProduct.
func (mr *MockStoreMockRecorder) AddOrderProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrderProduct", reflect.TypeOf((*MockStore)(nil).AddOrderProduct), arg0, arg1)
}

// AddPurchaseItem mocks base method.
func (m *MockStore) AddPurchaseItem(arg0 context.Context, arg1 db.AddPurchaseItemParams) (db.PurchaseItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPurchaseItem", arg0, arg1)
	ret0, _ := ret[0].(db.PurchaseItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPurchaseItem indicates an expected call of AddPurchaseItem.
func (mr *MockStoreMockRecorder) AddPurchaseItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPurchaseItem", reflect.TypeOf((*MockStore)(nil).AddPurchaseItem), arg0, arg1)
}

// AddSupplierProduct mocks base method.
func (m *MockStore) AddSupplierProduct(arg0 context.Context, arg1 db.AddSupplierProductParams) (db.ProductSupplier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSupplierProduct", arg0, arg1)
	ret0, _ := ret[0].(db.ProductSupplier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddSupplierProduct indicates an expected call of AddSupplierProduct.
func (mr *MockStoreMockRecorder) AddSupplierProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSupplierProduct", reflect.TypeOf((*MockStore)(nil).AddSupplierProduct), arg0, arg1)
}

// AddSupplierProductCost mocks base method.
func (m *MockStore) AddSupplierProductCost(arg0 context.Context, arg1 db.AddSupplierProductCostParams) (db.ProductSupplierCost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSupplierProductCost", arg0, arg1)
	ret0, _ := ret[0].(db.ProductSupplierCost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddSupplierProductCost indicates an expected call of AddSupplierProductCost.
func (mr *MockStoreMockRecorder) AddSupplierProductCost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSupplierProductCost", reflect.TypeOf((*MockStore)(nil).AddSupplierProductCost), arg0, arg1)
}

// CreateAttributeValue mocks base method.
func (m *MockStore) CreateAttributeValue(arg0 context.Context, arg1 db.CreateAttributeValueParams) (db.AttributesValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttributeValue", arg0, arg1)
	ret0, _ := ret[0].(db.AttributesValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAttributeValue indicates an expected call of CreateAttributeValue.
func (mr *MockStoreMockRecorder) CreateAttributeValue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttributeValue", reflect.TypeOf((*MockStore)(nil).CreateAttributeValue), arg0, arg1)
}

// CreateCurrency mocks base method.
func (m *MockStore) CreateCurrency(arg0 context.Context, arg1 db.CreateCurrencyParams) (db.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCurrency", arg0, arg1)
	ret0, _ := ret[0].(db.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCurrency indicates an expected call of CreateCurrency.
func (mr *MockStoreMockRecorder) CreateCurrency(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCurrency", reflect.TypeOf((*MockStore)(nil).CreateCurrency), arg0, arg1)
}

// CreateEntryItem mocks base method.
func (m *MockStore) CreateEntryItem(arg0 context.Context, arg1 db.CreateEntryItemParams) (db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEntryItem", arg0, arg1)
	ret0, _ := ret[0].(db.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEntryItem indicates an expected call of CreateEntryItem.
func (mr *MockStoreMockRecorder) CreateEntryItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEntryItem", reflect.TypeOf((*MockStore)(nil).CreateEntryItem), arg0, arg1)
}

// CreateInventory mocks base method.
func (m *MockStore) CreateInventory(arg0 context.Context, arg1 db.CreateInventoryParams) (db.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInventory", arg0, arg1)
	ret0, _ := ret[0].(db.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInventory indicates an expected call of CreateInventory.
func (mr *MockStoreMockRecorder) CreateInventory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInventory", reflect.TypeOf((*MockStore)(nil).CreateInventory), arg0, arg1)
}

// CreateOrder mocks base method.
func (m *MockStore) CreateOrder(arg0 context.Context, arg1 db.CreateOrderParams) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", arg0, arg1)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockStoreMockRecorder) CreateOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockStore)(nil).CreateOrder), arg0, arg1)
}

// CreateProduct mocks base method.
func (m *MockStore) CreateProduct(arg0 context.Context, arg1 db.CreateProductParams) (db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", arg0, arg1)
	ret0, _ := ret[0].(db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockStoreMockRecorder) CreateProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockStore)(nil).CreateProduct), arg0, arg1)
}

// CreateProductAttribute mocks base method.
func (m *MockStore) CreateProductAttribute(arg0 context.Context, arg1 db.CreateProductAttributeParams) (db.ProductsAttribute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProductAttribute", arg0, arg1)
	ret0, _ := ret[0].(db.ProductsAttribute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProductAttribute indicates an expected call of CreateProductAttribute.
func (mr *MockStoreMockRecorder) CreateProductAttribute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProductAttribute", reflect.TypeOf((*MockStore)(nil).CreateProductAttribute), arg0, arg1)
}

// CreateProductEntry mocks base method.
func (m *MockStore) CreateProductEntry(arg0 context.Context, arg1 db.CreateProductEntryParams) (db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProductEntry", arg0, arg1)
	ret0, _ := ret[0].(db.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProductEntry indicates an expected call of CreateProductEntry.
func (mr *MockStoreMockRecorder) CreateProductEntry(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProductEntry", reflect.TypeOf((*MockStore)(nil).CreateProductEntry), arg0, arg1)
}

// CreatePurchase mocks base method.
func (m *MockStore) CreatePurchase(arg0 context.Context, arg1 db.CreatePurchaseParams) (db.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePurchase", arg0, arg1)
	ret0, _ := ret[0].(db.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePurchase indicates an expected call of CreatePurchase.
func (mr *MockStoreMockRecorder) CreatePurchase(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePurchase", reflect.TypeOf((*MockStore)(nil).CreatePurchase), arg0, arg1)
}

// CreateSupplier mocks base method.
func (m *MockStore) CreateSupplier(arg0 context.Context, arg1 db.CreateSupplierParams) (db.Supplier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSupplier", arg0, arg1)
	ret0, _ := ret[0].(db.Supplier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSupplier indicates an expected call of CreateSupplier.
func (mr *MockStoreMockRecorder) CreateSupplier(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSupplier", reflect.TypeOf((*MockStore)(nil).CreateSupplier), arg0, arg1)
}

// CreateTransfer mocks base method.
func (m *MockStore) CreateTransfer(arg0 context.Context, arg1 db.CreateTransferParams) (db.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransfer", arg0, arg1)
	ret0, _ := ret[0].(db.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransfer indicates an expected call of CreateTransfer.
func (mr *MockStoreMockRecorder) CreateTransfer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransfer", reflect.TypeOf((*MockStore)(nil).CreateTransfer), arg0, arg1)
}

// CreateTransferItem mocks base method.
func (m *MockStore) CreateTransferItem(arg0 context.Context, arg1 db.CreateTransferItemParams) (db.TransferItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransferItem", arg0, arg1)
	ret0, _ := ret[0].(db.TransferItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransferItem indicates an expected call of CreateTransferItem.
func (mr *MockStoreMockRecorder) CreateTransferItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransferItem", reflect.TypeOf((*MockStore)(nil).CreateTransferItem), arg0, arg1)
}

// DeleteCurrency mocks base method.
func (m *MockStore) DeleteCurrency(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCurrency", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCurrency indicates an expected call of DeleteCurrency.
func (mr *MockStoreMockRecorder) DeleteCurrency(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCurrency", reflect.TypeOf((*MockStore)(nil).DeleteCurrency), arg0, arg1)
}

// DeleteInventory mocks base method.
func (m *MockStore) DeleteInventory(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInventory", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInventory indicates an expected call of DeleteInventory.
func (mr *MockStoreMockRecorder) DeleteInventory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInventory", reflect.TypeOf((*MockStore)(nil).DeleteInventory), arg0, arg1)
}

// DeleteInventoryProduct mocks base method.
func (m *MockStore) DeleteInventoryProduct(arg0 context.Context, arg1 db.DeleteInventoryProductParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInventoryProduct", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInventoryProduct indicates an expected call of DeleteInventoryProduct.
func (mr *MockStoreMockRecorder) DeleteInventoryProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInventoryProduct", reflect.TypeOf((*MockStore)(nil).DeleteInventoryProduct), arg0, arg1)
}

// DeleteProduct mocks base method.
func (m *MockStore) DeleteProduct(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockStoreMockRecorder) DeleteProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockStore)(nil).DeleteProduct), arg0, arg1)
}

// DeletePurchaseItem mocks base method.
func (m *MockStore) DeletePurchaseItem(arg0 context.Context, arg1 db.DeletePurchaseItemParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePurchaseItem", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePurchaseItem indicates an expected call of DeletePurchaseItem.
func (mr *MockStoreMockRecorder) DeletePurchaseItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePurchaseItem", reflect.TypeOf((*MockStore)(nil).DeletePurchaseItem), arg0, arg1)
}

// DeleteSupplierProduct mocks base method.
func (m *MockStore) DeleteSupplierProduct(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSupplierProduct", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSupplierProduct indicates an expected call of DeleteSupplierProduct.
func (mr *MockStoreMockRecorder) DeleteSupplierProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSupplierProduct", reflect.TypeOf((*MockStore)(nil).DeleteSupplierProduct), arg0, arg1)
}

// GetAttributeValue mocks base method.
func (m *MockStore) GetAttributeValue(arg0 context.Context, arg1 int64) (db.AttributesValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttributeValue", arg0, arg1)
	ret0, _ := ret[0].(db.AttributesValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttributeValue indicates an expected call of GetAttributeValue.
func (mr *MockStoreMockRecorder) GetAttributeValue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttributeValue", reflect.TypeOf((*MockStore)(nil).GetAttributeValue), arg0, arg1)
}

// GetCurrency mocks base method.
func (m *MockStore) GetCurrency(arg0 context.Context, arg1 int64) (db.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrency", arg0, arg1)
	ret0, _ := ret[0].(db.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrency indicates an expected call of GetCurrency.
func (mr *MockStoreMockRecorder) GetCurrency(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrency", reflect.TypeOf((*MockStore)(nil).GetCurrency), arg0, arg1)
}

// GetEntry mocks base method.
func (m *MockStore) GetEntry(arg0 context.Context, arg1 int64) (db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntry", arg0, arg1)
	ret0, _ := ret[0].(db.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntry indicates an expected call of GetEntry.
func (mr *MockStoreMockRecorder) GetEntry(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntry", reflect.TypeOf((*MockStore)(nil).GetEntry), arg0, arg1)
}

// GetInventory mocks base method.
func (m *MockStore) GetInventory(arg0 context.Context, arg1 int64) (db.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInventory", arg0, arg1)
	ret0, _ := ret[0].(db.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInventory indicates an expected call of GetInventory.
func (mr *MockStoreMockRecorder) GetInventory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInventory", reflect.TypeOf((*MockStore)(nil).GetInventory), arg0, arg1)
}

// GetOrder mocks base method.
func (m *MockStore) GetOrder(arg0 context.Context, arg1 int64) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", arg0, arg1)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockStoreMockRecorder) GetOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockStore)(nil).GetOrder), arg0, arg1)
}

// GetProduct mocks base method.
func (m *MockStore) GetProduct(arg0 context.Context, arg1 int64) (db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", arg0, arg1)
	ret0, _ := ret[0].(db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockStoreMockRecorder) GetProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockStore)(nil).GetProduct), arg0, arg1)
}

// GetProductAttributeValue mocks base method.
func (m *MockStore) GetProductAttributeValue(arg0 context.Context, arg1 db.GetProductAttributeValueParams) (db.ProductsAttribute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductAttributeValue", arg0, arg1)
	ret0, _ := ret[0].(db.ProductsAttribute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductAttributeValue indicates an expected call of GetProductAttributeValue.
func (mr *MockStoreMockRecorder) GetProductAttributeValue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductAttributeValue", reflect.TypeOf((*MockStore)(nil).GetProductAttributeValue), arg0, arg1)
}

// GetPurchase mocks base method.
func (m *MockStore) GetPurchase(arg0 context.Context, arg1 int64) (db.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPurchase", arg0, arg1)
	ret0, _ := ret[0].(db.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPurchase indicates an expected call of GetPurchase.
func (mr *MockStoreMockRecorder) GetPurchase(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPurchase", reflect.TypeOf((*MockStore)(nil).GetPurchase), arg0, arg1)
}

// GetSupplier mocks base method.
func (m *MockStore) GetSupplier(arg0 context.Context, arg1 int64) (db.Supplier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupplier", arg0, arg1)
	ret0, _ := ret[0].(db.Supplier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupplier indicates an expected call of GetSupplier.
func (mr *MockStoreMockRecorder) GetSupplier(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupplier", reflect.TypeOf((*MockStore)(nil).GetSupplier), arg0, arg1)
}

// GetTransfer mocks base method.
func (m *MockStore) GetTransfer(arg0 context.Context, arg1 int64) (db.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransfer", arg0, arg1)
	ret0, _ := ret[0].(db.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransfer indicates an expected call of GetTransfer.
func (mr *MockStoreMockRecorder) GetTransfer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransfer", reflect.TypeOf((*MockStore)(nil).GetTransfer), arg0, arg1)
}

// ListAttributeValues mocks base method.
func (m *MockStore) ListAttributeValues(arg0 context.Context, arg1 db.ListAttributeValuesParams) ([]db.ListAttributeValuesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAttributeValues", arg0, arg1)
	ret0, _ := ret[0].([]db.ListAttributeValuesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAttributeValues indicates an expected call of ListAttributeValues.
func (mr *MockStoreMockRecorder) ListAttributeValues(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAttributeValues", reflect.TypeOf((*MockStore)(nil).ListAttributeValues), arg0, arg1)
}

// ListCurrencies mocks base method.
func (m *MockStore) ListCurrencies(arg0 context.Context, arg1 db.ListCurrenciesParams) ([]db.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCurrencies", arg0, arg1)
	ret0, _ := ret[0].([]db.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCurrencies indicates an expected call of ListCurrencies.
func (mr *MockStoreMockRecorder) ListCurrencies(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCurrencies", reflect.TypeOf((*MockStore)(nil).ListCurrencies), arg0, arg1)
}

// ListEntries mocks base method.
func (m *MockStore) ListEntries(arg0 context.Context, arg1 db.ListEntriesParams) ([]db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEntries", arg0, arg1)
	ret0, _ := ret[0].([]db.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEntries indicates an expected call of ListEntries.
func (mr *MockStoreMockRecorder) ListEntries(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEntries", reflect.TypeOf((*MockStore)(nil).ListEntries), arg0, arg1)
}

// ListInventories mocks base method.
func (m *MockStore) ListInventories(arg0 context.Context, arg1 db.ListInventoriesParams) ([]db.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInventories", arg0, arg1)
	ret0, _ := ret[0].([]db.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInventories indicates an expected call of ListInventories.
func (mr *MockStoreMockRecorder) ListInventories(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInventories", reflect.TypeOf((*MockStore)(nil).ListInventories), arg0, arg1)
}

// ListInventoryProducts mocks base method.
func (m *MockStore) ListInventoryProducts(arg0 context.Context, arg1 int64) ([]db.ListInventoryProductsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInventoryProducts", arg0, arg1)
	ret0, _ := ret[0].([]db.ListInventoryProductsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInventoryProducts indicates an expected call of ListInventoryProducts.
func (mr *MockStoreMockRecorder) ListInventoryProducts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInventoryProducts", reflect.TypeOf((*MockStore)(nil).ListInventoryProducts), arg0, arg1)
}

// ListOrders mocks base method.
func (m *MockStore) ListOrders(arg0 context.Context, arg1 db.ListOrdersParams) ([]db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrders", arg0, arg1)
	ret0, _ := ret[0].([]db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrders indicates an expected call of ListOrders.
func (mr *MockStoreMockRecorder) ListOrders(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrders", reflect.TypeOf((*MockStore)(nil).ListOrders), arg0, arg1)
}

// ListProductAttributes mocks base method.
func (m *MockStore) ListProductAttributes(arg0 context.Context, arg1 db.ListProductAttributesParams) ([]db.ProductsAttribute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProductAttributes", arg0, arg1)
	ret0, _ := ret[0].([]db.ProductsAttribute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProductAttributes indicates an expected call of ListProductAttributes.
func (mr *MockStoreMockRecorder) ListProductAttributes(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProductAttributes", reflect.TypeOf((*MockStore)(nil).ListProductAttributes), arg0, arg1)
}

// ListProducts mocks base method.
func (m *MockStore) ListProducts(arg0 context.Context, arg1 db.ListProductsParams) ([]db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", arg0, arg1)
	ret0, _ := ret[0].([]db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockStoreMockRecorder) ListProducts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockStore)(nil).ListProducts), arg0, arg1)
}

// ListPurchases mocks base method.
func (m *MockStore) ListPurchases(arg0 context.Context, arg1 db.ListPurchasesParams) ([]db.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPurchases", arg0, arg1)
	ret0, _ := ret[0].([]db.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPurchases indicates an expected call of ListPurchases.
func (mr *MockStoreMockRecorder) ListPurchases(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPurchases", reflect.TypeOf((*MockStore)(nil).ListPurchases), arg0, arg1)
}

// ListSuppliers mocks base method.
func (m *MockStore) ListSuppliers(arg0 context.Context, arg1 db.ListSuppliersParams) ([]db.Supplier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSuppliers", arg0, arg1)
	ret0, _ := ret[0].([]db.Supplier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSuppliers indicates an expected call of ListSuppliers.
func (mr *MockStoreMockRecorder) ListSuppliers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSuppliers", reflect.TypeOf((*MockStore)(nil).ListSuppliers), arg0, arg1)
}

// ListTransferItems mocks base method.
func (m *MockStore) ListTransferItems(arg0 context.Context, arg1 int64) ([]db.ListTransferItemsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransferItems", arg0, arg1)
	ret0, _ := ret[0].([]db.ListTransferItemsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransferItems indicates an expected call of ListTransferItems.
func (mr *MockStoreMockRecorder) ListTransferItems(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransferItems", reflect.TypeOf((*MockStore)(nil).ListTransferItems), arg0, arg1)
}

// ListTransfers mocks base method.
func (m *MockStore) ListTransfers(arg0 context.Context, arg1 db.ListTransfersParams) ([]db.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransfers", arg0, arg1)
	ret0, _ := ret[0].([]db.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransfers indicates an expected call of ListTransfers.
func (mr *MockStoreMockRecorder) ListTransfers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransfers", reflect.TypeOf((*MockStore)(nil).ListTransfers), arg0, arg1)
}

// TransferTx mocks base method.
func (m *MockStore) TransferTx(arg0 context.Context, arg1 db.TransferTxParams) (db.TransferTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TransferTx", arg0, arg1)
	ret0, _ := ret[0].(db.TransferTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TransferTx indicates an expected call of TransferTx.
func (mr *MockStoreMockRecorder) TransferTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TransferTx", reflect.TypeOf((*MockStore)(nil).TransferTx), arg0, arg1)
}

// UpdateAttributeValue mocks base method.
func (m *MockStore) UpdateAttributeValue(arg0 context.Context, arg1 db.UpdateAttributeValueParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAttributeValue", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAttributeValue indicates an expected call of UpdateAttributeValue.
func (mr *MockStoreMockRecorder) UpdateAttributeValue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAttributeValue", reflect.TypeOf((*MockStore)(nil).UpdateAttributeValue), arg0, arg1)
}

// UpdateInventory mocks base method.
func (m *MockStore) UpdateInventory(arg0 context.Context, arg1 db.UpdateInventoryParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInventory", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInventory indicates an expected call of UpdateInventory.
func (mr *MockStoreMockRecorder) UpdateInventory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInventory", reflect.TypeOf((*MockStore)(nil).UpdateInventory), arg0, arg1)
}

// UpdateInventoryProduct mocks base method.
func (m *MockStore) UpdateInventoryProduct(arg0 context.Context, arg1 db.UpdateInventoryProductParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInventoryProduct", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInventoryProduct indicates an expected call of UpdateInventoryProduct.
func (mr *MockStoreMockRecorder) UpdateInventoryProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInventoryProduct", reflect.TypeOf((*MockStore)(nil).UpdateInventoryProduct), arg0, arg1)
}

// UpdateProduct mocks base method.
func (m *MockStore) UpdateProduct(arg0 context.Context, arg1 db.UpdateProductParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockStoreMockRecorder) UpdateProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockStore)(nil).UpdateProduct), arg0, arg1)
}

// UpdateProductAttribute mocks base method.
func (m *MockStore) UpdateProductAttribute(arg0 context.Context, arg1 db.UpdateProductAttributeParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductAttribute", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProductAttribute indicates an expected call of UpdateProductAttribute.
func (mr *MockStoreMockRecorder) UpdateProductAttribute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductAttribute", reflect.TypeOf((*MockStore)(nil).UpdateProductAttribute), arg0, arg1)
}

// UpdateTransfer mocks base method.
func (m *MockStore) UpdateTransfer(arg0 context.Context, arg1 db.UpdateTransferParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransfer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransfer indicates an expected call of UpdateTransfer.
func (mr *MockStoreMockRecorder) UpdateTransfer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransfer", reflect.TypeOf((*MockStore)(nil).UpdateTransfer), arg0, arg1)
}
