// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mhdna/kashi/db/sqlc (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	db "github.com/mhdna/kashi/db/sqlc"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddInventoryProduct mocks base method.
func (m *MockStore) AddInventoryProduct(arg0 context.Context, arg1 db.AddInventoryProductParams) (db.InventoriesProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddInventoryProduct", arg0, arg1)
	ret0, _ := ret[0].(db.InventoriesProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddInventoryProduct indicates an expected call of AddInventoryProduct.
func (mr *MockStoreMockRecorder) AddInventoryProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInventoryProduct", reflect.TypeOf((*MockStore)(nil).AddInventoryProduct), arg0, arg1)
}

// AddPurchaseItem mocks base method.
func (m *MockStore) AddPurchaseItem(arg0 context.Context, arg1 db.AddPurchaseItemParams) (db.PurchaseItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPurchaseItem", arg0, arg1)
	ret0, _ := ret[0].(db.PurchaseItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPurchaseItem indicates an expected call of AddPurchaseItem.
func (mr *MockStoreMockRecorder) AddPurchaseItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPurchaseItem", reflect.TypeOf((*MockStore)(nil).AddPurchaseItem), arg0, arg1)
}

// AddSalesInvoiceProduct mocks base method.
func (m *MockStore) AddSalesInvoiceProduct(arg0 context.Context, arg1 db.AddSalesInvoiceProductParams) (db.SalesInvoiceProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSalesInvoiceProduct", arg0, arg1)
	ret0, _ := ret[0].(db.SalesInvoiceProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddSalesInvoiceProduct indicates an expected call of AddSalesInvoiceProduct.
func (mr *MockStoreMockRecorder) AddSalesInvoiceProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSalesInvoiceProduct", reflect.TypeOf((*MockStore)(nil).AddSalesInvoiceProduct), arg0, arg1)
}

// AddSupplierProduct mocks base method.
func (m *MockStore) AddSupplierProduct(arg0 context.Context, arg1 db.AddSupplierProductParams) (db.ProductSupplier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSupplierProduct", arg0, arg1)
	ret0, _ := ret[0].(db.ProductSupplier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddSupplierProduct indicates an expected call of AddSupplierProduct.
func (mr *MockStoreMockRecorder) AddSupplierProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSupplierProduct", reflect.TypeOf((*MockStore)(nil).AddSupplierProduct), arg0, arg1)
}

// AddSupplierProductCost mocks base method.
func (m *MockStore) AddSupplierProductCost(arg0 context.Context, arg1 db.AddSupplierProductCostParams) (db.ProductSupplierCost, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddSupplierProductCost", arg0, arg1)
	ret0, _ := ret[0].(db.ProductSupplierCost)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddSupplierProductCost indicates an expected call of AddSupplierProductCost.
func (mr *MockStoreMockRecorder) AddSupplierProductCost(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddSupplierProductCost", reflect.TypeOf((*MockStore)(nil).AddSupplierProductCost), arg0, arg1)
}

// CloseShift mocks base method.
func (m *MockStore) CloseShift(arg0 context.Context, arg1 db.CloseShiftParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloseShift", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// CloseShift indicates an expected call of CloseShift.
func (mr *MockStoreMockRecorder) CloseShift(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloseShift", reflect.TypeOf((*MockStore)(nil).CloseShift), arg0, arg1)
}

// CreateAttributeValue mocks base method.
func (m *MockStore) CreateAttributeValue(arg0 context.Context, arg1 db.CreateAttributeValueParams) (db.AttributesValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttributeValue", arg0, arg1)
	ret0, _ := ret[0].(db.AttributesValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAttributeValue indicates an expected call of CreateAttributeValue.
func (mr *MockStoreMockRecorder) CreateAttributeValue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttributeValue", reflect.TypeOf((*MockStore)(nil).CreateAttributeValue), arg0, arg1)
}

// CreateCashBoxAccount mocks base method.
func (m *MockStore) CreateCashBoxAccount(arg0 context.Context, arg1 string) (db.CashboxAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCashBoxAccount", arg0, arg1)
	ret0, _ := ret[0].(db.CashboxAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCashBoxAccount indicates an expected call of CreateCashBoxAccount.
func (mr *MockStoreMockRecorder) CreateCashBoxAccount(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCashBoxAccount", reflect.TypeOf((*MockStore)(nil).CreateCashBoxAccount), arg0, arg1)
}

// CreateCashbox mocks base method.
func (m *MockStore) CreateCashbox(arg0 context.Context, arg1 db.CreateCashboxParams) (db.Cashbox, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCashbox", arg0, arg1)
	ret0, _ := ret[0].(db.Cashbox)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCashbox indicates an expected call of CreateCashbox.
func (mr *MockStoreMockRecorder) CreateCashbox(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCashbox", reflect.TypeOf((*MockStore)(nil).CreateCashbox), arg0, arg1)
}

// CreateClient mocks base method.
func (m *MockStore) CreateClient(arg0 context.Context, arg1 db.CreateClientParams) (db.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClient", arg0, arg1)
	ret0, _ := ret[0].(db.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateClient indicates an expected call of CreateClient.
func (mr *MockStoreMockRecorder) CreateClient(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClient", reflect.TypeOf((*MockStore)(nil).CreateClient), arg0, arg1)
}

// CreateCurrency mocks base method.
func (m *MockStore) CreateCurrency(arg0 context.Context, arg1 db.CreateCurrencyParams) (db.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCurrency", arg0, arg1)
	ret0, _ := ret[0].(db.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCurrency indicates an expected call of CreateCurrency.
func (mr *MockStoreMockRecorder) CreateCurrency(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCurrency", reflect.TypeOf((*MockStore)(nil).CreateCurrency), arg0, arg1)
}

// CreateEntryItem mocks base method.
func (m *MockStore) CreateEntryItem(arg0 context.Context, arg1 db.CreateEntryItemParams) (db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEntryItem", arg0, arg1)
	ret0, _ := ret[0].(db.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEntryItem indicates an expected call of CreateEntryItem.
func (mr *MockStoreMockRecorder) CreateEntryItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEntryItem", reflect.TypeOf((*MockStore)(nil).CreateEntryItem), arg0, arg1)
}

// CreateExpense mocks base method.
func (m *MockStore) CreateExpense(arg0 context.Context, arg1 db.CreateExpenseParams) (db.Expense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateExpense", arg0, arg1)
	ret0, _ := ret[0].(db.Expense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateExpense indicates an expected call of CreateExpense.
func (mr *MockStoreMockRecorder) CreateExpense(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateExpense", reflect.TypeOf((*MockStore)(nil).CreateExpense), arg0, arg1)
}

// CreateInventory mocks base method.
func (m *MockStore) CreateInventory(arg0 context.Context, arg1 db.CreateInventoryParams) (db.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInventory", arg0, arg1)
	ret0, _ := ret[0].(db.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInventory indicates an expected call of CreateInventory.
func (mr *MockStoreMockRecorder) CreateInventory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInventory", reflect.TypeOf((*MockStore)(nil).CreateInventory), arg0, arg1)
}

// CreateProduct mocks base method.
func (m *MockStore) CreateProduct(arg0 context.Context, arg1 db.CreateProductParams) (db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", arg0, arg1)
	ret0, _ := ret[0].(db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockStoreMockRecorder) CreateProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockStore)(nil).CreateProduct), arg0, arg1)
}

// CreateProductAttribute mocks base method.
func (m *MockStore) CreateProductAttribute(arg0 context.Context, arg1 db.CreateProductAttributeParams) (db.ProductsAttribute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProductAttribute", arg0, arg1)
	ret0, _ := ret[0].(db.ProductsAttribute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProductAttribute indicates an expected call of CreateProductAttribute.
func (mr *MockStoreMockRecorder) CreateProductAttribute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProductAttribute", reflect.TypeOf((*MockStore)(nil).CreateProductAttribute), arg0, arg1)
}

// CreatePurchase mocks base method.
func (m *MockStore) CreatePurchase(arg0 context.Context, arg1 db.CreatePurchaseParams) (db.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePurchase", arg0, arg1)
	ret0, _ := ret[0].(db.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePurchase indicates an expected call of CreatePurchase.
func (mr *MockStoreMockRecorder) CreatePurchase(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePurchase", reflect.TypeOf((*MockStore)(nil).CreatePurchase), arg0, arg1)
}

// CreateReturnInvoice mocks base method.
func (m *MockStore) CreateReturnInvoice(arg0 context.Context, arg1 db.CreateReturnInvoiceParams) (db.ReturnInvoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateReturnInvoice", arg0, arg1)
	ret0, _ := ret[0].(db.ReturnInvoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateReturnInvoice indicates an expected call of CreateReturnInvoice.
func (mr *MockStoreMockRecorder) CreateReturnInvoice(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateReturnInvoice", reflect.TypeOf((*MockStore)(nil).CreateReturnInvoice), arg0, arg1)
}

// CreateSalesInvoice mocks base method.
func (m *MockStore) CreateSalesInvoice(arg0 context.Context, arg1 db.CreateSalesInvoiceParams) (db.SalesInvoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSalesInvoice", arg0, arg1)
	ret0, _ := ret[0].(db.SalesInvoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSalesInvoice indicates an expected call of CreateSalesInvoice.
func (mr *MockStoreMockRecorder) CreateSalesInvoice(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSalesInvoice", reflect.TypeOf((*MockStore)(nil).CreateSalesInvoice), arg0, arg1)
}

// CreateShift mocks base method.
func (m *MockStore) CreateShift(arg0 context.Context, arg1 db.CreateShiftParams) (db.Shift, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateShift", arg0, arg1)
	ret0, _ := ret[0].(db.Shift)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateShift indicates an expected call of CreateShift.
func (mr *MockStoreMockRecorder) CreateShift(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateShift", reflect.TypeOf((*MockStore)(nil).CreateShift), arg0, arg1)
}

// CreateSupplier mocks base method.
func (m *MockStore) CreateSupplier(arg0 context.Context, arg1 db.CreateSupplierParams) (db.Supplier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSupplier", arg0, arg1)
	ret0, _ := ret[0].(db.Supplier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSupplier indicates an expected call of CreateSupplier.
func (mr *MockStoreMockRecorder) CreateSupplier(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSupplier", reflect.TypeOf((*MockStore)(nil).CreateSupplier), arg0, arg1)
}

// CreateTransfer mocks base method.
func (m *MockStore) CreateTransfer(arg0 context.Context, arg1 db.CreateTransferParams) (db.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransfer", arg0, arg1)
	ret0, _ := ret[0].(db.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransfer indicates an expected call of CreateTransfer.
func (mr *MockStoreMockRecorder) CreateTransfer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransfer", reflect.TypeOf((*MockStore)(nil).CreateTransfer), arg0, arg1)
}

// CreateTransferItem mocks base method.
func (m *MockStore) CreateTransferItem(arg0 context.Context, arg1 db.CreateTransferItemParams) (db.TransferItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTransferItem", arg0, arg1)
	ret0, _ := ret[0].(db.TransferItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTransferItem indicates an expected call of CreateTransferItem.
func (mr *MockStoreMockRecorder) CreateTransferItem(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTransferItem", reflect.TypeOf((*MockStore)(nil).CreateTransferItem), arg0, arg1)
}

// DeleteClient mocks base method.
func (m *MockStore) DeleteClient(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClient", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteClient indicates an expected call of DeleteClient.
func (mr *MockStoreMockRecorder) DeleteClient(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClient", reflect.TypeOf((*MockStore)(nil).DeleteClient), arg0, arg1)
}

// DeleteCurrency mocks base method.
func (m *MockStore) DeleteCurrency(arg0 context.Context, arg1 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteCurrency", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteCurrency indicates an expected call of DeleteCurrency.
func (mr *MockStoreMockRecorder) DeleteCurrency(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteCurrency", reflect.TypeOf((*MockStore)(nil).DeleteCurrency), arg0, arg1)
}

// DeleteInventory mocks base method.
func (m *MockStore) DeleteInventory(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInventory", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInventory indicates an expected call of DeleteInventory.
func (mr *MockStoreMockRecorder) DeleteInventory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInventory", reflect.TypeOf((*MockStore)(nil).DeleteInventory), arg0, arg1)
}

// DeleteInventoryProduct mocks base method.
func (m *MockStore) DeleteInventoryProduct(arg0 context.Context, arg1 db.DeleteInventoryProductParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInventoryProduct", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInventoryProduct indicates an expected call of DeleteInventoryProduct.
func (mr *MockStoreMockRecorder) DeleteInventoryProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInventoryProduct", reflect.TypeOf((*MockStore)(nil).DeleteInventoryProduct), arg0, arg1)
}

// DeleteProduct mocks base method.
func (m *MockStore) DeleteProduct(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockStoreMockRecorder) DeleteProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockStore)(nil).DeleteProduct), arg0, arg1)
}

// DeleteSupplierProduct mocks base method.
func (m *MockStore) DeleteSupplierProduct(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSupplierProduct", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSupplierProduct indicates an expected call of DeleteSupplierProduct.
func (mr *MockStoreMockRecorder) DeleteSupplierProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSupplierProduct", reflect.TypeOf((*MockStore)(nil).DeleteSupplierProduct), arg0, arg1)
}

// GetAccountBalance mocks base method.
func (m *MockStore) GetAccountBalance(arg0 context.Context, arg1 db.GetAccountBalanceParams) (db.AccountsBalance, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccountBalance", arg0, arg1)
	ret0, _ := ret[0].(db.AccountsBalance)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccountBalance indicates an expected call of GetAccountBalance.
func (mr *MockStoreMockRecorder) GetAccountBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccountBalance", reflect.TypeOf((*MockStore)(nil).GetAccountBalance), arg0, arg1)
}

// GetAttributeValue mocks base method.
func (m *MockStore) GetAttributeValue(arg0 context.Context, arg1 int64) (db.AttributesValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttributeValue", arg0, arg1)
	ret0, _ := ret[0].(db.AttributesValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttributeValue indicates an expected call of GetAttributeValue.
func (mr *MockStoreMockRecorder) GetAttributeValue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttributeValue", reflect.TypeOf((*MockStore)(nil).GetAttributeValue), arg0, arg1)
}

// GetCashbox mocks base method.
func (m *MockStore) GetCashbox(arg0 context.Context, arg1 int64) (db.Cashbox, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCashbox", arg0, arg1)
	ret0, _ := ret[0].(db.Cashbox)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCashbox indicates an expected call of GetCashbox.
func (mr *MockStoreMockRecorder) GetCashbox(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCashbox", reflect.TypeOf((*MockStore)(nil).GetCashbox), arg0, arg1)
}

// GetClient mocks base method.
func (m *MockStore) GetClient(arg0 context.Context, arg1 int64) (db.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", arg0, arg1)
	ret0, _ := ret[0].(db.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockStoreMockRecorder) GetClient(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockStore)(nil).GetClient), arg0, arg1)
}

// GetCurrency mocks base method.
func (m *MockStore) GetCurrency(arg0 context.Context, arg1 string) (db.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrency", arg0, arg1)
	ret0, _ := ret[0].(db.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrency indicates an expected call of GetCurrency.
func (mr *MockStoreMockRecorder) GetCurrency(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrency", reflect.TypeOf((*MockStore)(nil).GetCurrency), arg0, arg1)
}

// GetDefaultCurrency mocks base method.
func (m *MockStore) GetDefaultCurrency(arg0 context.Context) (db.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDefaultCurrency", arg0)
	ret0, _ := ret[0].(db.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDefaultCurrency indicates an expected call of GetDefaultCurrency.
func (mr *MockStoreMockRecorder) GetDefaultCurrency(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDefaultCurrency", reflect.TypeOf((*MockStore)(nil).GetDefaultCurrency), arg0)
}

// GetEntry mocks base method.
func (m *MockStore) GetEntry(arg0 context.Context, arg1 int64) (db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntry", arg0, arg1)
	ret0, _ := ret[0].(db.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntry indicates an expected call of GetEntry.
func (mr *MockStoreMockRecorder) GetEntry(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntry", reflect.TypeOf((*MockStore)(nil).GetEntry), arg0, arg1)
}

// GetExpense mocks base method.
func (m *MockStore) GetExpense(arg0 context.Context, arg1 int64) (db.Expense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpense", arg0, arg1)
	ret0, _ := ret[0].(db.Expense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetExpense indicates an expected call of GetExpense.
func (mr *MockStoreMockRecorder) GetExpense(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpense", reflect.TypeOf((*MockStore)(nil).GetExpense), arg0, arg1)
}

// GetInventory mocks base method.
func (m *MockStore) GetInventory(arg0 context.Context, arg1 int64) (db.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInventory", arg0, arg1)
	ret0, _ := ret[0].(db.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInventory indicates an expected call of GetInventory.
func (mr *MockStoreMockRecorder) GetInventory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInventory", reflect.TypeOf((*MockStore)(nil).GetInventory), arg0, arg1)
}

// GetProduct mocks base method.
func (m *MockStore) GetProduct(arg0 context.Context, arg1 int64) (db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", arg0, arg1)
	ret0, _ := ret[0].(db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockStoreMockRecorder) GetProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockStore)(nil).GetProduct), arg0, arg1)
}

// GetProductAttributeValue mocks base method.
func (m *MockStore) GetProductAttributeValue(arg0 context.Context, arg1 db.GetProductAttributeValueParams) (db.ProductsAttribute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductAttributeValue", arg0, arg1)
	ret0, _ := ret[0].(db.ProductsAttribute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductAttributeValue indicates an expected call of GetProductAttributeValue.
func (mr *MockStoreMockRecorder) GetProductAttributeValue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductAttributeValue", reflect.TypeOf((*MockStore)(nil).GetProductAttributeValue), arg0, arg1)
}

// GetPurchase mocks base method.
func (m *MockStore) GetPurchase(arg0 context.Context, arg1 int64) (db.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPurchase", arg0, arg1)
	ret0, _ := ret[0].(db.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPurchase indicates an expected call of GetPurchase.
func (mr *MockStoreMockRecorder) GetPurchase(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPurchase", reflect.TypeOf((*MockStore)(nil).GetPurchase), arg0, arg1)
}

// GetReturnInvoice mocks base method.
func (m *MockStore) GetReturnInvoice(arg0 context.Context, arg1 int64) (db.ReturnInvoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetReturnInvoice", arg0, arg1)
	ret0, _ := ret[0].(db.ReturnInvoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetReturnInvoice indicates an expected call of GetReturnInvoice.
func (mr *MockStoreMockRecorder) GetReturnInvoice(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetReturnInvoice", reflect.TypeOf((*MockStore)(nil).GetReturnInvoice), arg0, arg1)
}

// GetSalesInvoice mocks base method.
func (m *MockStore) GetSalesInvoice(arg0 context.Context, arg1 int64) (db.SalesInvoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSalesInvoice", arg0, arg1)
	ret0, _ := ret[0].(db.SalesInvoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSalesInvoice indicates an expected call of GetSalesInvoice.
func (mr *MockStoreMockRecorder) GetSalesInvoice(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSalesInvoice", reflect.TypeOf((*MockStore)(nil).GetSalesInvoice), arg0, arg1)
}

// GetShift mocks base method.
func (m *MockStore) GetShift(arg0 context.Context, arg1 int64) (db.Shift, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetShift", arg0, arg1)
	ret0, _ := ret[0].(db.Shift)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetShift indicates an expected call of GetShift.
func (mr *MockStoreMockRecorder) GetShift(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetShift", reflect.TypeOf((*MockStore)(nil).GetShift), arg0, arg1)
}

// GetSupplier mocks base method.
func (m *MockStore) GetSupplier(arg0 context.Context, arg1 int64) (db.Supplier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSupplier", arg0, arg1)
	ret0, _ := ret[0].(db.Supplier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSupplier indicates an expected call of GetSupplier.
func (mr *MockStoreMockRecorder) GetSupplier(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSupplier", reflect.TypeOf((*MockStore)(nil).GetSupplier), arg0, arg1)
}

// GetTransfer mocks base method.
func (m *MockStore) GetTransfer(arg0 context.Context, arg1 int64) (db.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransfer", arg0, arg1)
	ret0, _ := ret[0].(db.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransfer indicates an expected call of GetTransfer.
func (mr *MockStoreMockRecorder) GetTransfer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransfer", reflect.TypeOf((*MockStore)(nil).GetTransfer), arg0, arg1)
}

// ListAttributeValues mocks base method.
func (m *MockStore) ListAttributeValues(arg0 context.Context, arg1 db.ListAttributeValuesParams) ([]db.ListAttributeValuesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAttributeValues", arg0, arg1)
	ret0, _ := ret[0].([]db.ListAttributeValuesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAttributeValues indicates an expected call of ListAttributeValues.
func (mr *MockStoreMockRecorder) ListAttributeValues(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAttributeValues", reflect.TypeOf((*MockStore)(nil).ListAttributeValues), arg0, arg1)
}

// ListCashboxes mocks base method.
func (m *MockStore) ListCashboxes(arg0 context.Context, arg1 db.ListCashboxesParams) ([]db.Cashbox, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCashboxes", arg0, arg1)
	ret0, _ := ret[0].([]db.Cashbox)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCashboxes indicates an expected call of ListCashboxes.
func (mr *MockStoreMockRecorder) ListCashboxes(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCashboxes", reflect.TypeOf((*MockStore)(nil).ListCashboxes), arg0, arg1)
}

// ListClients mocks base method.
func (m *MockStore) ListClients(arg0 context.Context, arg1 db.ListClientsParams) ([]db.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListClients", arg0, arg1)
	ret0, _ := ret[0].([]db.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListClients indicates an expected call of ListClients.
func (mr *MockStoreMockRecorder) ListClients(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListClients", reflect.TypeOf((*MockStore)(nil).ListClients), arg0, arg1)
}

// ListCurrencies mocks base method.
func (m *MockStore) ListCurrencies(arg0 context.Context, arg1 db.ListCurrenciesParams) ([]db.Currency, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListCurrencies", arg0, arg1)
	ret0, _ := ret[0].([]db.Currency)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListCurrencies indicates an expected call of ListCurrencies.
func (mr *MockStoreMockRecorder) ListCurrencies(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListCurrencies", reflect.TypeOf((*MockStore)(nil).ListCurrencies), arg0, arg1)
}

// ListEntries mocks base method.
func (m *MockStore) ListEntries(arg0 context.Context, arg1 db.ListEntriesParams) ([]db.Entry, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListEntries", arg0, arg1)
	ret0, _ := ret[0].([]db.Entry)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListEntries indicates an expected call of ListEntries.
func (mr *MockStoreMockRecorder) ListEntries(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListEntries", reflect.TypeOf((*MockStore)(nil).ListEntries), arg0, arg1)
}

// ListExpenses mocks base method.
func (m *MockStore) ListExpenses(arg0 context.Context, arg1 db.ListExpensesParams) ([]db.Expense, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListExpenses", arg0, arg1)
	ret0, _ := ret[0].([]db.Expense)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListExpenses indicates an expected call of ListExpenses.
func (mr *MockStoreMockRecorder) ListExpenses(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListExpenses", reflect.TypeOf((*MockStore)(nil).ListExpenses), arg0, arg1)
}

// ListInventories mocks base method.
func (m *MockStore) ListInventories(arg0 context.Context, arg1 db.ListInventoriesParams) ([]db.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInventories", arg0, arg1)
	ret0, _ := ret[0].([]db.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInventories indicates an expected call of ListInventories.
func (mr *MockStoreMockRecorder) ListInventories(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInventories", reflect.TypeOf((*MockStore)(nil).ListInventories), arg0, arg1)
}

// ListInventoryProducts mocks base method.
func (m *MockStore) ListInventoryProducts(arg0 context.Context, arg1 int64) ([]db.ListInventoryProductsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInventoryProducts", arg0, arg1)
	ret0, _ := ret[0].([]db.ListInventoryProductsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInventoryProducts indicates an expected call of ListInventoryProducts.
func (mr *MockStoreMockRecorder) ListInventoryProducts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInventoryProducts", reflect.TypeOf((*MockStore)(nil).ListInventoryProducts), arg0, arg1)
}

// ListProductAttributes mocks base method.
func (m *MockStore) ListProductAttributes(arg0 context.Context, arg1 db.ListProductAttributesParams) ([]db.ProductsAttribute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProductAttributes", arg0, arg1)
	ret0, _ := ret[0].([]db.ProductsAttribute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProductAttributes indicates an expected call of ListProductAttributes.
func (mr *MockStoreMockRecorder) ListProductAttributes(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProductAttributes", reflect.TypeOf((*MockStore)(nil).ListProductAttributes), arg0, arg1)
}

// ListProducts mocks base method.
func (m *MockStore) ListProducts(arg0 context.Context, arg1 db.ListProductsParams) ([]db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", arg0, arg1)
	ret0, _ := ret[0].([]db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockStoreMockRecorder) ListProducts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockStore)(nil).ListProducts), arg0, arg1)
}

// ListPurchases mocks base method.
func (m *MockStore) ListPurchases(arg0 context.Context, arg1 db.ListPurchasesParams) ([]db.Purchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPurchases", arg0, arg1)
	ret0, _ := ret[0].([]db.Purchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPurchases indicates an expected call of ListPurchases.
func (mr *MockStoreMockRecorder) ListPurchases(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPurchases", reflect.TypeOf((*MockStore)(nil).ListPurchases), arg0, arg1)
}

// ListSalesInvoices mocks base method.
func (m *MockStore) ListSalesInvoices(arg0 context.Context, arg1 db.ListSalesInvoicesParams) ([]db.SalesInvoice, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSalesInvoices", arg0, arg1)
	ret0, _ := ret[0].([]db.SalesInvoice)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSalesInvoices indicates an expected call of ListSalesInvoices.
func (mr *MockStoreMockRecorder) ListSalesInvoices(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSalesInvoices", reflect.TypeOf((*MockStore)(nil).ListSalesInvoices), arg0, arg1)
}

// ListShifts mocks base method.
func (m *MockStore) ListShifts(arg0 context.Context, arg1 db.ListShiftsParams) ([]db.Shift, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListShifts", arg0, arg1)
	ret0, _ := ret[0].([]db.Shift)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListShifts indicates an expected call of ListShifts.
func (mr *MockStoreMockRecorder) ListShifts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListShifts", reflect.TypeOf((*MockStore)(nil).ListShifts), arg0, arg1)
}

// ListSuppliers mocks base method.
func (m *MockStore) ListSuppliers(arg0 context.Context, arg1 db.ListSuppliersParams) ([]db.Supplier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSuppliers", arg0, arg1)
	ret0, _ := ret[0].([]db.Supplier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListSuppliers indicates an expected call of ListSuppliers.
func (mr *MockStoreMockRecorder) ListSuppliers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSuppliers", reflect.TypeOf((*MockStore)(nil).ListSuppliers), arg0, arg1)
}

// ListTransferItems mocks base method.
func (m *MockStore) ListTransferItems(arg0 context.Context, arg1 int64) ([]db.ListTransferItemsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransferItems", arg0, arg1)
	ret0, _ := ret[0].([]db.ListTransferItemsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransferItems indicates an expected call of ListTransferItems.
func (mr *MockStoreMockRecorder) ListTransferItems(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransferItems", reflect.TypeOf((*MockStore)(nil).ListTransferItems), arg0, arg1)
}

// ListTransfers mocks base method.
func (m *MockStore) ListTransfers(arg0 context.Context, arg1 db.ListTransfersParams) ([]db.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTransfers", arg0, arg1)
	ret0, _ := ret[0].([]db.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTransfers indicates an expected call of ListTransfers.
func (mr *MockStoreMockRecorder) ListTransfers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTransfers", reflect.TypeOf((*MockStore)(nil).ListTransfers), arg0, arg1)
}

// NextReturnInvoiceIndexIncrement mocks base method.
func (m *MockStore) NextReturnInvoiceIndexIncrement(arg0 context.Context, arg1 db.NextReturnInvoiceIndexIncrementParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextReturnInvoiceIndexIncrement", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextReturnInvoiceIndexIncrement indicates an expected call of NextReturnInvoiceIndexIncrement.
func (mr *MockStoreMockRecorder) NextReturnInvoiceIndexIncrement(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextReturnInvoiceIndexIncrement", reflect.TypeOf((*MockStore)(nil).NextReturnInvoiceIndexIncrement), arg0, arg1)
}

// NextSalesInvoiceIndexIncrement mocks base method.
func (m *MockStore) NextSalesInvoiceIndexIncrement(arg0 context.Context, arg1 db.NextSalesInvoiceIndexIncrementParams) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextSalesInvoiceIndexIncrement", arg0, arg1)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NextSalesInvoiceIndexIncrement indicates an expected call of NextSalesInvoiceIndexIncrement.
func (mr *MockStoreMockRecorder) NextSalesInvoiceIndexIncrement(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextSalesInvoiceIndexIncrement", reflect.TypeOf((*MockStore)(nil).NextSalesInvoiceIndexIncrement), arg0, arg1)
}

// SalesInvoiceTx mocks base method.
func (m *MockStore) SalesInvoiceTx(arg0 context.Context, arg1 db.SalesInvoiceTxParams) (db.SalesInvoiceTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SalesInvoiceTx", arg0, arg1)
	ret0, _ := ret[0].(db.SalesInvoiceTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SalesInvoiceTx indicates an expected call of SalesInvoiceTx.
func (mr *MockStoreMockRecorder) SalesInvoiceTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SalesInvoiceTx", reflect.TypeOf((*MockStore)(nil).SalesInvoiceTx), arg0, arg1)
}

// UpdateAccountBalance mocks base method.
func (m *MockStore) UpdateAccountBalance(arg0 context.Context, arg1 db.UpdateAccountBalanceParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAccountBalance", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAccountBalance indicates an expected call of UpdateAccountBalance.
func (mr *MockStoreMockRecorder) UpdateAccountBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAccountBalance", reflect.TypeOf((*MockStore)(nil).UpdateAccountBalance), arg0, arg1)
}

// UpdateAttributeValue mocks base method.
func (m *MockStore) UpdateAttributeValue(arg0 context.Context, arg1 db.UpdateAttributeValueParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAttributeValue", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAttributeValue indicates an expected call of UpdateAttributeValue.
func (mr *MockStoreMockRecorder) UpdateAttributeValue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAttributeValue", reflect.TypeOf((*MockStore)(nil).UpdateAttributeValue), arg0, arg1)
}

// UpdateClient mocks base method.
func (m *MockStore) UpdateClient(arg0 context.Context, arg1 db.UpdateClientParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClient", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateClient indicates an expected call of UpdateClient.
func (mr *MockStoreMockRecorder) UpdateClient(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClient", reflect.TypeOf((*MockStore)(nil).UpdateClient), arg0, arg1)
}

// UpdateInventory mocks base method.
func (m *MockStore) UpdateInventory(arg0 context.Context, arg1 db.UpdateInventoryParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInventory", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInventory indicates an expected call of UpdateInventory.
func (mr *MockStoreMockRecorder) UpdateInventory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInventory", reflect.TypeOf((*MockStore)(nil).UpdateInventory), arg0, arg1)
}

// UpdateInventoryProduct mocks base method.
func (m *MockStore) UpdateInventoryProduct(arg0 context.Context, arg1 db.UpdateInventoryProductParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInventoryProduct", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInventoryProduct indicates an expected call of UpdateInventoryProduct.
func (mr *MockStoreMockRecorder) UpdateInventoryProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInventoryProduct", reflect.TypeOf((*MockStore)(nil).UpdateInventoryProduct), arg0, arg1)
}

// UpdateProduct mocks base method.
func (m *MockStore) UpdateProduct(arg0 context.Context, arg1 db.UpdateProductParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockStoreMockRecorder) UpdateProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockStore)(nil).UpdateProduct), arg0, arg1)
}

// UpdateProductAttribute mocks base method.
func (m *MockStore) UpdateProductAttribute(arg0 context.Context, arg1 db.UpdateProductAttributeParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductAttribute", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProductAttribute indicates an expected call of UpdateProductAttribute.
func (mr *MockStoreMockRecorder) UpdateProductAttribute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductAttribute", reflect.TypeOf((*MockStore)(nil).UpdateProductAttribute), arg0, arg1)
}

// UpdateShiftBalance mocks base method.
func (m *MockStore) UpdateShiftBalance(arg0 context.Context, arg1 db.UpdateShiftBalanceParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateShiftBalance", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateShiftBalance indicates an expected call of UpdateShiftBalance.
func (mr *MockStoreMockRecorder) UpdateShiftBalance(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateShiftBalance", reflect.TypeOf((*MockStore)(nil).UpdateShiftBalance), arg0, arg1)
}

// UpdateTransfer mocks base method.
func (m *MockStore) UpdateTransfer(arg0 context.Context, arg1 db.UpdateTransferParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTransfer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTransfer indicates an expected call of UpdateTransfer.
func (mr *MockStoreMockRecorder) UpdateTransfer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTransfer", reflect.TypeOf((*MockStore)(nil).UpdateTransfer), arg0, arg1)
}
