// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/mhdna/kashi/db/sqlc (interfaces: Store)

// Package mockdb is a generated GoMock package.
package mockdb

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	db "github.com/mhdna/kashi/db/sqlc"
)

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// AddInventoryProduct mocks base method.
func (m *MockStore) AddInventoryProduct(arg0 context.Context, arg1 db.AddInventoryProductParams) (db.InventoriesProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddInventoryProduct", arg0, arg1)
	ret0, _ := ret[0].(db.InventoriesProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddInventoryProduct indicates an expected call of AddInventoryProduct.
func (mr *MockStoreMockRecorder) AddInventoryProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddInventoryProduct", reflect.TypeOf((*MockStore)(nil).AddInventoryProduct), arg0, arg1)
}

// AddOrderProduct mocks base method.
func (m *MockStore) AddOrderProduct(arg0 context.Context, arg1 db.AddOrderProductParams) (db.OrdersProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddOrderProduct", arg0, arg1)
	ret0, _ := ret[0].(db.OrdersProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddOrderProduct indicates an expected call of AddOrderProduct.
func (mr *MockStoreMockRecorder) AddOrderProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddOrderProduct", reflect.TypeOf((*MockStore)(nil).AddOrderProduct), arg0, arg1)
}

// CreateATransfer mocks base method.
func (m *MockStore) CreateATransfer(arg0 context.Context, arg1 db.CreateATransferParams) (db.Atransfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateATransfer", arg0, arg1)
	ret0, _ := ret[0].(db.Atransfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateATransfer indicates an expected call of CreateATransfer.
func (mr *MockStoreMockRecorder) CreateATransfer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateATransfer", reflect.TypeOf((*MockStore)(nil).CreateATransfer), arg0, arg1)
}

// CreateATransferAsset mocks base method.
func (m *MockStore) CreateATransferAsset(arg0 context.Context, arg1 db.CreateATransferAssetParams) (db.AtransfersAsset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateATransferAsset", arg0, arg1)
	ret0, _ := ret[0].(db.AtransfersAsset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateATransferAsset indicates an expected call of CreateATransferAsset.
func (mr *MockStoreMockRecorder) CreateATransferAsset(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateATransferAsset", reflect.TypeOf((*MockStore)(nil).CreateATransferAsset), arg0, arg1)
}

// CreateAttributeValue mocks base method.
func (m *MockStore) CreateAttributeValue(arg0 context.Context, arg1 db.CreateAttributeValueParams) (db.AttributesValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAttributeValue", arg0, arg1)
	ret0, _ := ret[0].(db.AttributesValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateAttributeValue indicates an expected call of CreateAttributeValue.
func (mr *MockStoreMockRecorder) CreateAttributeValue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAttributeValue", reflect.TypeOf((*MockStore)(nil).CreateAttributeValue), arg0, arg1)
}

// CreateInventory mocks base method.
func (m *MockStore) CreateInventory(arg0 context.Context, arg1 db.CreateInventoryParams) (db.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateInventory", arg0, arg1)
	ret0, _ := ret[0].(db.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateInventory indicates an expected call of CreateInventory.
func (mr *MockStoreMockRecorder) CreateInventory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateInventory", reflect.TypeOf((*MockStore)(nil).CreateInventory), arg0, arg1)
}

// CreateOrder mocks base method.
func (m *MockStore) CreateOrder(arg0 context.Context, arg1 db.CreateOrderParams) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", arg0, arg1)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockStoreMockRecorder) CreateOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockStore)(nil).CreateOrder), arg0, arg1)
}

// CreatePTransfer mocks base method.
func (m *MockStore) CreatePTransfer(arg0 context.Context, arg1 db.CreatePTransferParams) (db.Ptransfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePTransfer", arg0, arg1)
	ret0, _ := ret[0].(db.Ptransfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePTransfer indicates an expected call of CreatePTransfer.
func (mr *MockStoreMockRecorder) CreatePTransfer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePTransfer", reflect.TypeOf((*MockStore)(nil).CreatePTransfer), arg0, arg1)
}

// CreatePTransferProduct mocks base method.
func (m *MockStore) CreatePTransferProduct(arg0 context.Context, arg1 db.CreatePTransferProductParams) (db.PtransfersProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePTransferProduct", arg0, arg1)
	ret0, _ := ret[0].(db.PtransfersProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePTransferProduct indicates an expected call of CreatePTransferProduct.
func (mr *MockStoreMockRecorder) CreatePTransferProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePTransferProduct", reflect.TypeOf((*MockStore)(nil).CreatePTransferProduct), arg0, arg1)
}

// CreateProduct mocks base method.
func (m *MockStore) CreateProduct(arg0 context.Context, arg1 db.CreateProductParams) (db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProduct", arg0, arg1)
	ret0, _ := ret[0].(db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProduct indicates an expected call of CreateProduct.
func (mr *MockStoreMockRecorder) CreateProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProduct", reflect.TypeOf((*MockStore)(nil).CreateProduct), arg0, arg1)
}

// CreateProductAttribute mocks base method.
func (m *MockStore) CreateProductAttribute(arg0 context.Context, arg1 db.CreateProductAttributeParams) (db.ProductsAttribute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateProductAttribute", arg0, arg1)
	ret0, _ := ret[0].(db.ProductsAttribute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateProductAttribute indicates an expected call of CreateProductAttribute.
func (mr *MockStoreMockRecorder) CreateProductAttribute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateProductAttribute", reflect.TypeOf((*MockStore)(nil).CreateProductAttribute), arg0, arg1)
}

// DeleteATransfer mocks base method.
func (m *MockStore) DeleteATransfer(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteATransfer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteATransfer indicates an expected call of DeleteATransfer.
func (mr *MockStoreMockRecorder) DeleteATransfer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteATransfer", reflect.TypeOf((*MockStore)(nil).DeleteATransfer), arg0, arg1)
}

// DeleteInventory mocks base method.
func (m *MockStore) DeleteInventory(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInventory", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInventory indicates an expected call of DeleteInventory.
func (mr *MockStoreMockRecorder) DeleteInventory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInventory", reflect.TypeOf((*MockStore)(nil).DeleteInventory), arg0, arg1)
}

// DeleteInventoryProduct mocks base method.
func (m *MockStore) DeleteInventoryProduct(arg0 context.Context, arg1 db.DeleteInventoryProductParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteInventoryProduct", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteInventoryProduct indicates an expected call of DeleteInventoryProduct.
func (mr *MockStoreMockRecorder) DeleteInventoryProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteInventoryProduct", reflect.TypeOf((*MockStore)(nil).DeleteInventoryProduct), arg0, arg1)
}

// DeletePTransfer mocks base method.
func (m *MockStore) DeletePTransfer(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePTransfer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePTransfer indicates an expected call of DeletePTransfer.
func (mr *MockStoreMockRecorder) DeletePTransfer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePTransfer", reflect.TypeOf((*MockStore)(nil).DeletePTransfer), arg0, arg1)
}

// DeleteProduct mocks base method.
func (m *MockStore) DeleteProduct(arg0 context.Context, arg1 int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteProduct", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteProduct indicates an expected call of DeleteProduct.
func (mr *MockStoreMockRecorder) DeleteProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteProduct", reflect.TypeOf((*MockStore)(nil).DeleteProduct), arg0, arg1)
}

// GetATransfer mocks base method.
func (m *MockStore) GetATransfer(arg0 context.Context, arg1 int64) (db.Atransfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetATransfer", arg0, arg1)
	ret0, _ := ret[0].(db.Atransfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetATransfer indicates an expected call of GetATransfer.
func (mr *MockStoreMockRecorder) GetATransfer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetATransfer", reflect.TypeOf((*MockStore)(nil).GetATransfer), arg0, arg1)
}

// GetAttributeValue mocks base method.
func (m *MockStore) GetAttributeValue(arg0 context.Context, arg1 int64) (db.AttributesValue, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttributeValue", arg0, arg1)
	ret0, _ := ret[0].(db.AttributesValue)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttributeValue indicates an expected call of GetAttributeValue.
func (mr *MockStoreMockRecorder) GetAttributeValue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttributeValue", reflect.TypeOf((*MockStore)(nil).GetAttributeValue), arg0, arg1)
}

// GetInventory mocks base method.
func (m *MockStore) GetInventory(arg0 context.Context, arg1 int64) (db.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInventory", arg0, arg1)
	ret0, _ := ret[0].(db.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetInventory indicates an expected call of GetInventory.
func (mr *MockStoreMockRecorder) GetInventory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInventory", reflect.TypeOf((*MockStore)(nil).GetInventory), arg0, arg1)
}

// GetOrder mocks base method.
func (m *MockStore) GetOrder(arg0 context.Context, arg1 int64) (db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", arg0, arg1)
	ret0, _ := ret[0].(db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockStoreMockRecorder) GetOrder(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockStore)(nil).GetOrder), arg0, arg1)
}

// GetPTransfer mocks base method.
func (m *MockStore) GetPTransfer(arg0 context.Context, arg1 int64) (db.Ptransfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPTransfer", arg0, arg1)
	ret0, _ := ret[0].(db.Ptransfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPTransfer indicates an expected call of GetPTransfer.
func (mr *MockStoreMockRecorder) GetPTransfer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPTransfer", reflect.TypeOf((*MockStore)(nil).GetPTransfer), arg0, arg1)
}

// GetPTransferProduct mocks base method.
func (m *MockStore) GetPTransferProduct(arg0 context.Context, arg1 db.GetPTransferProductParams) (db.PtransfersProduct, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPTransferProduct", arg0, arg1)
	ret0, _ := ret[0].(db.PtransfersProduct)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPTransferProduct indicates an expected call of GetPTransferProduct.
func (mr *MockStoreMockRecorder) GetPTransferProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPTransferProduct", reflect.TypeOf((*MockStore)(nil).GetPTransferProduct), arg0, arg1)
}

// GetProduct mocks base method.
func (m *MockStore) GetProduct(arg0 context.Context, arg1 int64) (db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProduct", arg0, arg1)
	ret0, _ := ret[0].(db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProduct indicates an expected call of GetProduct.
func (mr *MockStoreMockRecorder) GetProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProduct", reflect.TypeOf((*MockStore)(nil).GetProduct), arg0, arg1)
}

// GetProductAttributeValue mocks base method.
func (m *MockStore) GetProductAttributeValue(arg0 context.Context, arg1 db.GetProductAttributeValueParams) (db.ProductsAttribute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProductAttributeValue", arg0, arg1)
	ret0, _ := ret[0].(db.ProductsAttribute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProductAttributeValue indicates an expected call of GetProductAttributeValue.
func (mr *MockStoreMockRecorder) GetProductAttributeValue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProductAttributeValue", reflect.TypeOf((*MockStore)(nil).GetProductAttributeValue), arg0, arg1)
}

// ListATransferAssets mocks base method.
func (m *MockStore) ListATransferAssets(arg0 context.Context, arg1 int64) ([]db.ListATransferAssetsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListATransferAssets", arg0, arg1)
	ret0, _ := ret[0].([]db.ListATransferAssetsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListATransferAssets indicates an expected call of ListATransferAssets.
func (mr *MockStoreMockRecorder) ListATransferAssets(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListATransferAssets", reflect.TypeOf((*MockStore)(nil).ListATransferAssets), arg0, arg1)
}

// ListATransfers mocks base method.
func (m *MockStore) ListATransfers(arg0 context.Context, arg1 db.ListATransfersParams) ([]db.Atransfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListATransfers", arg0, arg1)
	ret0, _ := ret[0].([]db.Atransfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListATransfers indicates an expected call of ListATransfers.
func (mr *MockStoreMockRecorder) ListATransfers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListATransfers", reflect.TypeOf((*MockStore)(nil).ListATransfers), arg0, arg1)
}

// ListAttributeValues mocks base method.
func (m *MockStore) ListAttributeValues(arg0 context.Context, arg1 db.ListAttributeValuesParams) ([]db.ListAttributeValuesRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAttributeValues", arg0, arg1)
	ret0, _ := ret[0].([]db.ListAttributeValuesRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAttributeValues indicates an expected call of ListAttributeValues.
func (mr *MockStoreMockRecorder) ListAttributeValues(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAttributeValues", reflect.TypeOf((*MockStore)(nil).ListAttributeValues), arg0, arg1)
}

// ListInventories mocks base method.
func (m *MockStore) ListInventories(arg0 context.Context, arg1 db.ListInventoriesParams) ([]db.Inventory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInventories", arg0, arg1)
	ret0, _ := ret[0].([]db.Inventory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInventories indicates an expected call of ListInventories.
func (mr *MockStoreMockRecorder) ListInventories(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInventories", reflect.TypeOf((*MockStore)(nil).ListInventories), arg0, arg1)
}

// ListInventoryProducts mocks base method.
func (m *MockStore) ListInventoryProducts(arg0 context.Context, arg1 int64) ([]db.ListInventoryProductsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListInventoryProducts", arg0, arg1)
	ret0, _ := ret[0].([]db.ListInventoryProductsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListInventoryProducts indicates an expected call of ListInventoryProducts.
func (mr *MockStoreMockRecorder) ListInventoryProducts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListInventoryProducts", reflect.TypeOf((*MockStore)(nil).ListInventoryProducts), arg0, arg1)
}

// ListOrders mocks base method.
func (m *MockStore) ListOrders(arg0 context.Context, arg1 db.ListOrdersParams) ([]db.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListOrders", arg0, arg1)
	ret0, _ := ret[0].([]db.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListOrders indicates an expected call of ListOrders.
func (mr *MockStoreMockRecorder) ListOrders(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListOrders", reflect.TypeOf((*MockStore)(nil).ListOrders), arg0, arg1)
}

// ListPTransferProducts mocks base method.
func (m *MockStore) ListPTransferProducts(arg0 context.Context, arg1 int64) ([]db.ListPTransferProductsRow, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPTransferProducts", arg0, arg1)
	ret0, _ := ret[0].([]db.ListPTransferProductsRow)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPTransferProducts indicates an expected call of ListPTransferProducts.
func (mr *MockStoreMockRecorder) ListPTransferProducts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPTransferProducts", reflect.TypeOf((*MockStore)(nil).ListPTransferProducts), arg0, arg1)
}

// ListPTransfers mocks base method.
func (m *MockStore) ListPTransfers(arg0 context.Context, arg1 db.ListPTransfersParams) ([]db.Ptransfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPTransfers", arg0, arg1)
	ret0, _ := ret[0].([]db.Ptransfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPTransfers indicates an expected call of ListPTransfers.
func (mr *MockStoreMockRecorder) ListPTransfers(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPTransfers", reflect.TypeOf((*MockStore)(nil).ListPTransfers), arg0, arg1)
}

// ListProductAttributes mocks base method.
func (m *MockStore) ListProductAttributes(arg0 context.Context, arg1 db.ListProductAttributesParams) ([]db.ProductsAttribute, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProductAttributes", arg0, arg1)
	ret0, _ := ret[0].([]db.ProductsAttribute)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProductAttributes indicates an expected call of ListProductAttributes.
func (mr *MockStoreMockRecorder) ListProductAttributes(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProductAttributes", reflect.TypeOf((*MockStore)(nil).ListProductAttributes), arg0, arg1)
}

// ListProducts mocks base method.
func (m *MockStore) ListProducts(arg0 context.Context, arg1 db.ListProductsParams) ([]db.Product, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListProducts", arg0, arg1)
	ret0, _ := ret[0].([]db.Product)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListProducts indicates an expected call of ListProducts.
func (mr *MockStoreMockRecorder) ListProducts(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListProducts", reflect.TypeOf((*MockStore)(nil).ListProducts), arg0, arg1)
}

// PTransferTx mocks base method.
func (m *MockStore) PTransferTx(arg0 context.Context, arg1 db.PTransferTxParams) (db.PTransferTxResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PTransferTx", arg0, arg1)
	ret0, _ := ret[0].(db.PTransferTxResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PTransferTx indicates an expected call of PTransferTx.
func (mr *MockStoreMockRecorder) PTransferTx(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PTransferTx", reflect.TypeOf((*MockStore)(nil).PTransferTx), arg0, arg1)
}

// UpdateATransfer mocks base method.
func (m *MockStore) UpdateATransfer(arg0 context.Context, arg1 db.UpdateATransferParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateATransfer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateATransfer indicates an expected call of UpdateATransfer.
func (mr *MockStoreMockRecorder) UpdateATransfer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateATransfer", reflect.TypeOf((*MockStore)(nil).UpdateATransfer), arg0, arg1)
}

// UpdateAttributeValue mocks base method.
func (m *MockStore) UpdateAttributeValue(arg0 context.Context, arg1 db.UpdateAttributeValueParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAttributeValue", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAttributeValue indicates an expected call of UpdateAttributeValue.
func (mr *MockStoreMockRecorder) UpdateAttributeValue(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAttributeValue", reflect.TypeOf((*MockStore)(nil).UpdateAttributeValue), arg0, arg1)
}

// UpdateInventory mocks base method.
func (m *MockStore) UpdateInventory(arg0 context.Context, arg1 db.UpdateInventoryParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInventory", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInventory indicates an expected call of UpdateInventory.
func (mr *MockStoreMockRecorder) UpdateInventory(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInventory", reflect.TypeOf((*MockStore)(nil).UpdateInventory), arg0, arg1)
}

// UpdateInventoryProduct mocks base method.
func (m *MockStore) UpdateInventoryProduct(arg0 context.Context, arg1 db.UpdateInventoryProductParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInventoryProduct", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInventoryProduct indicates an expected call of UpdateInventoryProduct.
func (mr *MockStoreMockRecorder) UpdateInventoryProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInventoryProduct", reflect.TypeOf((*MockStore)(nil).UpdateInventoryProduct), arg0, arg1)
}

// UpdatePTransfer mocks base method.
func (m *MockStore) UpdatePTransfer(arg0 context.Context, arg1 db.UpdatePTransferParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePTransfer", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePTransfer indicates an expected call of UpdatePTransfer.
func (mr *MockStoreMockRecorder) UpdatePTransfer(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePTransfer", reflect.TypeOf((*MockStore)(nil).UpdatePTransfer), arg0, arg1)
}

// UpdateProduct mocks base method.
func (m *MockStore) UpdateProduct(arg0 context.Context, arg1 db.UpdateProductParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProduct", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProduct indicates an expected call of UpdateProduct.
func (mr *MockStoreMockRecorder) UpdateProduct(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProduct", reflect.TypeOf((*MockStore)(nil).UpdateProduct), arg0, arg1)
}

// UpdateProductAttribute mocks base method.
func (m *MockStore) UpdateProductAttribute(arg0 context.Context, arg1 db.UpdateProductAttributeParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProductAttribute", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateProductAttribute indicates an expected call of UpdateProductAttribute.
func (mr *MockStoreMockRecorder) UpdateProductAttribute(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProductAttribute", reflect.TypeOf((*MockStore)(nil).UpdateProductAttribute), arg0, arg1)
}
